#include "nomen.h"

static enum encoding enc = e_iso8859_1;

static char str_Language[] = "English";
static char str_OK[] = "OK";
static unichar_t mnemonic_OK[] = 'O';
static char str_Cancel[] = "Cancel";
static unichar_t mnemonic_Cancel[] = 'C';
static char str_Open[] = "Open";
static unichar_t mnemonic_Open[] = 'O';
static char str_Save[] = "Save";
static unichar_t mnemonic_Save[] = 'S';
static char str_Filter[] = "Filter";
static unichar_t mnemonic_Filter[] = 'F';
static char str_New[] = "New";
static unichar_t mnemonic_New[] = 'N';
static char str_Replace[] = "Replace";
static char str_Fileexists[] = "File Exists";
/* "File, %s, exists. Replace it?" */
static char str_Fileexistspre[] = "File, ";
static char str_Fileexistspost[] = ", exists. Replace it?";
static char str_Createdir[] = "Create directory...";
static char str_Dirname[] = "Directory name?";
static char str_Couldntcreatedir[] = "Couldn't create directory";
/* Menus ... */
static char str_File[] = "File";
static unichar_t mnemonic_File[] = 'F';
static char str_Edit[] = "Edit";
static unichar_t mnemonic_Edit[] = 'E';
static char str_Window[] = "Window";
static unichar_t mnemonic_Window[] = 'W';
static char str_Help[] = "Help";
static unichar_t mnemonic_Help[] = 'H';
static char str_Recent[] = "Recent";
static unichar_t mnemonic_Recent[] = 't';
static char str_Revertfile[] = "Revert File";
static unichar_t mnemonic_Revertfile[] = 'R';
static char str_Saveas[] = "Save as...";
static unichar_t mnemonic_Saveas[] = 'a';
static char str_Close[] = "Close";
static unichar_t mnemonic_Close[] = 'c';
static char str_Prefs[] = "Preferences...";
static unichar_t mnemonic_Prefs[] = 'e';
static char str_Quit[] = "Quit";
static unichar_t mnemonic_Quit[] = 'Q';
static char str_Undo[] = "Undo";
static unichar_t mnemonic_Undo[] = 'U';
static char str_Redo[] = "Redo";
static unichar_t mnemonic_Redo[] = 'R';
static char str_Cut[] = "Cut";
static unichar_t mnemonic_Cut[] = 't';
static char str_Copy[] = "Copy";
static unichar_t mnemonic_Copy[] = 'C';
static char str_Paste[] = "Paste";
static unichar_t mnemonic_Paste[] = 'P';
static char str_Clear[] = "Clear";
static unichar_t mnemonic_Clear[] = 'l';
static char str_Selectall[] = "Select All";
static unichar_t mnemonic_Selectall[] = 'A';

static char *str_TtfMod = "TtfMod";
    /* ttfview.c */
static char *str_OpenTtf = "Open TTF...";
    /* uiutil.c */
static char *str_Badnumberin = "Bad number in ";
    /* Table names */
static char *str_tbl_cmap = "Character to glyph mapping\nSpecifies the font's encoding";
static char *str_tbl_glyf = "Glyph data\nSpecifies the glyphs in the font";
static char *str_tbl_head = "Font header\nGeneral information about the font";
static char *str_tbl_hhea = "Horizontal header\nHigh level information about the font's\nhorizontal metrics";
static char *str_tbl_hmtx = "Horizontal metrics\nHorizontal metric (lbearing/width)\ninformation for each character";
static char *str_tbl_loca = "Index to location\nPointers specifying where each glyph\nbegins in the glyf table";
static char *str_tbl_maxp = "Maximum profile\nSpecifies various maxima of the font";
static char *str_tbl_name = "Naming table\nSpecifies the font name, copyright, etc.";
static char *str_tbl_post = "PostScript data\nSpecifies PostScript specific data\nand PostScript glyph names";
static char *str_tbl_OS2  = "OS/2 and Windows specific metrics";
static char *str_tbl_cvt  = "Control Value Table\nVarious integers used for instructing\n(hinting) the font";
static char *str_tbl_EBDT = "Embedded bitmap data";
static char *str_tbl_EBLC = "Embedded bitmap location data";
static char *str_tbl_EBSC = "Embedded bitmap scaling data";
static char *str_tbl_fpgm = "Font Program\nInvoked before the first use of the font.";
static char *str_tbl_gasp = "grid-fitting and scan conversion procedure (greyscale)";
static char *str_tbl_hdmx = "Horizontal device metrics\nPrecomputed metrics for certain point-sizes";
static char *str_tbl_kern = "Kerning\nKerning pairs";
static char *str_tbl_LTSH = "Linear threshold table\nSpecifies point at which metrics may be\nassumed to scale from htmx table";
static char *str_tbl_prep = "CVT Program\nInvoked before each time the font is rasterized.";
static char *str_tbl_PCLT = "PCL5\nInformation for HP printers";
static char *str_tbl_VDMX = "Vertical Device Metrics table\nPrecomputed metrics for certain point-sizes";
static char *str_tbl_vhea = "Vertical header\nHigh level information about the font's\nvertical metrics (for CJK fonts)";
static char *str_tbl_vmtx = "Vertical metrics";
static char *str_tbl_CFF  = "Compact Font Format\nPostscript outlines";
static char *str_tbl_fvar = "Obsolete multiple master table"
static char *str_tbl_MMSD = "Obsolete multiple master table"
static char *str_tbl_MMFX = "Obsolete multiple master table"
static char *str_tbl_BASE = "Baseline data\nSpecifies how to align glyphs from different scripts";
static char *str_tbl_GDEF = "Glyph definition data\nSpecifies caret locations inside ligatures\nand attachment points";
static char *str_tbl_GPOS = "Glyph positioning data\nSpecifies how to positions glyphs with\nrespect to each other in caligraphic and other\ncomplex scripts";
static char *str_tbl_GSUB = "Glyph substitution data\nSpecifies ligatures, alternate glyphs,\npositional variants, contextual substitutions";
static char *str_tbl_JSTF = "Justification data\nAnother set of glyph substitutions\nspecifically for justification";
static char *str_tbl_DSIG = "Digital Signature";
static char *str_tbl_VORG = "Vertical Origin";

    /* maxp */
static char *str_Version = "Version:";
static char mnemonic_Version = 'V';
static char *str_Glyphs = "Glyphs:";
static char mnemonic_Glyphs = 'G';
static char *str_Points = "Points:";
static char mnemonic_Points = 'P';
static char *str_Contours = "Contours:";
static char mnemonic_Contours = 'C';
static char *str_CompositPoints = "Composit Pts:";
static char mnemonic_CompositPoints = 'n';
static char *str_CompositContours = "Composit Cntrs:";
static char mnemonic_CompositContours = 'r';
static char *str_Zones = "Zones:";
static char mnemonic_Zones = 'Z';
static char *str_TwilightPoints = "Twilight Pts:";
static char mnemonic_TwilightPoints = 'T';
static char *str_Storage = "Storage:";
static char mnemonic_Storage = 'S';
static char *str_FDEFs = "FDEFs:";
static char mnemonic_FDEFs = 'F';
static char *str_IDEFs = "IDEFs:";
static char mnemonic_IDEFs = 'I';
static char *str_StackElements = "Stack Els:";
static char mnemonic_StackElements = 'E';
static char *str_SizeOfInstructions = "Size Of Instrs:";
static char mnemonic_SizeOfInstructions = 'u';
static char *str_ComponentElements = "Component Els:";
static char mnemonic_ComponentElements = 'l';
static char *str_ComponentDepth = "CDepth:";
static char mnemonic_ComponentDepth = 'D';

static int num_buttonsize = 55;
