.\"	man page for ttfmod by george
.Dd October 20, 2001
.Dt TTFMOD 1
.Os
.Sh NAME
.Nm ttfmod
.Nd modify TrueType fonts
.Sh SYNOPSIS
.Nm
.Ar fontname
.Sh DESCRIPTION
.Nm
allows you to modify TrueType fonts. The intent is to give you access to tables
that you cannot get to from PfaEdit. At the moment all it really does is let
you look at tables.
.Pp
If a
.Ar fontname
is given,
.Nm
will open a font view looking at each font you selected. This may be a  true type
font (.ttf), a truetype collection (.ttc) or an opentype font (.otf).
.Pp
Without flags or arguments,
.Nm
will open a file picker dialog and allow you to browse your disk to find the
appropriate font file, or create a new one.
.\" .Sh ENVIRONMENT
.Sh FILES
.Bl -tag -width /usr/share/ttfmod/*.ui -compact
.It Pa /usr/share/ttfmod/*.ui
translations for the user interface
.El
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.Sh SEE ALSO
The ttfmod user manual, at
.Pa http://pfaedit.sourceforge.net/TtfMod
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHOR
George Williams
.Sh BUGS
No doubt many. But unknown (and ever changing).
