/* This file contains the SIL OPEN FONT LICENSE translated into as many */
/*  languages as I can find. */

#include <stdio.h>
#include "ofl.h"

static char *ofl_eng[] = {
    "Copyright (c) %1$d, %2$s (<URL|email>),",
    "with Reserved Font Name %3$s.",
    "",
    "This Font Software is licensed under the SIL Open Font License, Version 1.1.",
    "This license is copied below, and is also available with a FAQ at:",
    "http://scripts.sil.org/OFL",
    "",
    "",
    "-----------------------------------------------------------",
    "SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007",
    "-----------------------------------------------------------",
    "",
    "PREAMBLE",
    "The goals of the Open Font License (OFL) are to stimulate worldwide",
    "development of collaborative font projects, to support the font creation",
    "efforts of academic and linguistic communities, and to provide a free and",
    "open framework in which fonts may be shared and improved in partnership",
    "with others.",
    "",
    "The OFL allows the licensed fonts to be used, studied, modified and",
    "redistributed freely as long as they are not sold by themselves. The",
    "fonts, including any derivative works, can be bundled, embedded, ",
    "redistributed and/or sold with any software provided that any reserved",
    "names are not used by derivative works. The fonts and derivatives,",
    "however, cannot be released under any other type of license. The",
    "requirement for fonts to remain under this license does not apply",
    "to any document created using the fonts or their derivatives.",
    "",
    "DEFINITIONS",
    "\"Font Software\" refers to the set of files released by the Copyright",
    "Holder(s) under this license and clearly marked as such. This may",
    "include source files, build scripts and documentation.",
    "",
    "\"Reserved Font Name\" refers to any names specified as such after the",
    "copyright statement(s).",
    "",
    "\"Original Version\" refers to the collection of Font Software components as",
    "distributed by the Copyright Holder(s).",
    "",
    "\"Modified Version\" refers to any derivative made by adding to, deleting,",
    "or substituting -- in part or in whole -- any of the components of the",
    "Original Version, by changing formats or by porting the Font Software to a",
    "new environment.",
    "",
    "\"Author\" refers to any designer, engineer, programmer, technical",
    "writer or other person who contributed to the Font Software.",
    "",
    "PERMISSION & CONDITIONS",
    "Permission is hereby granted, free of charge, to any person obtaining",
    "a copy of the Font Software, to use, study, copy, merge, embed, modify,",
    "redistribute, and sell modified and unmodified copies of the Font",
    "Software, subject to the following conditions:",
    "",
    "1) Neither the Font Software nor any of its individual components,",
    "in Original or Modified Versions, may be sold by itself.",
    "",
    "2) Original or Modified Versions of the Font Software may be bundled,",
    "redistributed and/or sold with any software, provided that each copy",
    "contains the above copyright notice and this license. These can be",
    "included either as stand-alone text files, human-readable headers or",
    "in the appropriate machine-readable metadata fields within text or",
    "binary files as long as those fields can be easily viewed by the user.",
    "",
    "3) No Modified Version of the Font Software may use the Reserved Font",
    "Name(s) unless explicit written permission is granted by the corresponding",
    "Copyright Holder. This restriction only applies to the primary font name as",
    "presented to the users.",
    "",
    "4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font",
    "Software shall not be used to promote, endorse or advertise any",
    "Modified Version, except to acknowledge the contribution(s) of the",
    "Copyright Holder(s) and the Author(s) or with their explicit written",
    "permission.",
    "",
    "5) The Font Software, modified or unmodified, in part or in whole,",
    "must be distributed entirely under this license, and must not be",
    "distributed under any other license. The requirement for fonts to",
    "remain under this license does not apply to any document created",
    "using the Font Software.",
    "",
    "TERMINATION",
    "This license becomes null and void if any of the above conditions are",
    "not met.",
    "",
    "DISCLAIMER",
    "THE FONT SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,",
    "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF",
    "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT",
    "OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE",
    "COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,",
    "INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL",
    "DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING",
    "FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM",
    "OTHER DEALINGS IN THE FONT SOFTWARE.",
    NULL
};

static char *oflurl_eng[] = {
    "http://scripts.sil.org/ofl",
    NULL
};

static char *ofl_fr[] = {
    "Copyright (c) %1$d, %2$s (<URL|courriel>),",
    "avec le nom réservé suivant %3$s.",
    "",
    "Avertissement légal",
    "",
    "Cette traduction française de la licence pour les fontes libres de SIL",
    "(SIL Open Font Licence, ou encore OFL) n'est pas une traduction officielle.",
    "Elle n'a pas été publiée par SIL International et n'a pas de valeur légale",
    "pour la distribution des fontes sous OFL: seul le texte anglais original fait",
    "foi.",
    "",
    "Cependant, nous reconnaissons que cette traduction, même sans valeur légale,",
    "peut aider les utilisateurs et les créateurs non anglophones à mieux",
    "comprendre la licence SIL OFL, et faciliter la création et l'utilisation de",
    "polices de caractères selon son modèle de dessin collaboratif.",
    "",
    "Nous encourageons les créateurs qui envisagent de licencier leur travail sous OFL à lire la FAQ dans leur langue si elle est disponible. S'il vous plaît, allez sur le site http://scripts.sil.org/FAQ pour lire la version officielle de cette licence et la FAQ afférante.",
    "",
    "",
    "Cette fonte informatique est licenciée sous la licence SIL Open Font Licence, Version 1.1",
    "",
    "Cette licence figure ci dessous, et est aussi disponible,",
    "ainsi qu'une FAQ, à l'adresse: http://scripts.sil.org/OFL",
    "",
    "-----------------------------------------------------------",
    "SIL OPEN FONT LICENCE Version 1.1 - 26 Février 2007",
    "-----------------------------------------------------------",
    "",
    "PRÉAMBULE DU TRADUCTEUR",
    "",
    "l'appellation anglaise OFL a été conservée pour éviter d'introduire",
    "un nouvel acronyme. De même, le mot fonte a été utilisé, comme",
    "synonyme de police de caractère.",
    "",
    "PRÉAMBULE",
    "",
    "Le but de la licence OFL est de stimuler le développement collaboratif",
    "de fontes à travers le monde, d'aider à la création de fontes dans",
    "les communautés académiques ou linguistiques, et de fournir un cadre",
    "libre et ouvert à travers lequel ces fontes peuvent être partagées",
    "et améliorées de manière collective.",
    "",
    "Les fontes sous licence OFL peuvent être utilisées, étudiées, modifiées",
    "et redistribuées librement, tant qu'elles ne sont pas vendues par elles-même.",
    "Les fontes, ainsi que tous leurs dérivés, peuvent être fournies avec,",
    "incorporées, redistribuées et/ou vendues avec des logiciels quelconques,",
    "sous réserve que les appellations réservées ne soient pas utilisées",
    "dans les produits dérivés. La licence des fontes et de leurs produits",
    "dérivés ne peut cependant pas être modifiée. Cette obligation de",
    "conserver la licence OFL pour les fontes et leurs produits dérivés",
    "ne s'applique pas aux documents crées avec.",
    "",
    "DÉFINITIONS",
    "",
    "l'appellation 'fonte informatique' désigne l'ensemble des fichiers mis",
    "à disposition par le(s) titulaire(s) du copyright sous cette licence",
    "et clairement identifiés comme tels. Cela peut inclure des sources,",
    "des scripts de génération, de la documentation.",
    "",
    "l'appellation 'nom de fonte réservé' désigne n'importe quel nom",
    "désigné comme tel dans le copyright.",
    "",
    "'Version originale' désigne une 'fonte informatique' telle que",
    "distribuée par le(s) titulaire(s) du copyright.",
    "",
    "'Version modifiée' désigne tout travail dérivé obtenu en ajoutant,",
    "supprimant ou remplaçant tout ou partie de n'importe quel élément",
    "de la 'version originale', en changeant de format ou en portant",
    "la 'fonte informatique' vers un nouvel environnement.",
    "",
    "'l'Auteur' désigne un créateur, ingénieur, programmeur, auteur",
    "technique ou tout autre personne ayant contribué à la 'fonte",
    "informatique'.",
    "",
    "PERMISSIONS ET CONDITIONS",
    "",
    "La permission est ici accordée, sans contrepartie, à toute personne",
    "ayant obtenu une copie de la 'fonte informatique' de l'utiliser,",
    "l'étudier, la copier, la fusionner, l'inclure, la modifier, la",
    "redistribuer et la vendre, modifiée ou non, aux conditions suivantes:",
    "",
    "1) La 'fonte informatique', en tout ou partie, en version originale",
    "ou modifiée, ne peut être vendue par elle même.",
    "",
    "2) Les versions originales ou modifiées de la 'fonte informatique'",
    "peuvent être liées, redistribuées et/ou vendues avec n'importe quel",
    "logiciel, à condition que chaque copie contienne la déclaration de",
    "copyright ci-dessus ainsi que cette licence. Ces pièces peuvent",
    "être soit des fichiers textes autonomes, des entêtes de fichiers",
    "accessibles à un lecteur humain, ou figurer dans des méta-données",
    "accessibles par programme, dans des fichiers textes ou binaires,",
    "tant que leur texte est facilement accessible à un utilisateur.",
    "",
    "3) Aucune version modifiée de la 'fonte informatique' ne peut",
    "utiliser les noms réservés sans autorisation écrite expresse",
    "du propriétaire du copyright. Cette restriction ne s'applique",
    "qu'au nom principal de la police tel que présenté à l'utilisateur.",
    "",
    "4) le ou les noms du titulaire du copyright et ceux du ou des",
    "auteurs ne peuvent pas être utilisés pour promouvoir, conseiller",
    "ou faire de la publicité pour des versions modifiées, sauf pour",
    "rappeler leur(s) contribution(s), ou alors avec leur autorisation",
    "écrite expresse.",
    "",
    "5) La 'fonte informatique', modifiée ou non, en tout ou partie,",
    "doit être distribuée avec exactement cette même licence. Cette",
    "obligation de conserver la licence ne s'applique pas aux documents",
    "crées en utilisant la 'fonte informatique'.",
    "",
    "FIN DE CONTRAT",
    "",
    "Cette licence devient nulle et sans objet si l'une quelconque",
    "des conditions ci dessus n'est pas remplie.",
    "",
    "CLAUSE DE NON RESPONSABILITÉ",
    "",
    "LA FONTE INFORMATIQUE EST FOURNIE TELLE QUELLE, SANS GARANTIE",
    "D'AUCUNE SORTE, NI IMPLICITE NI EXPLICITE, Y COMPRIS ET DE",
    "MANIÈRE NON LIMITATIVE SANS GARANTIE DE COMMERCIABILITÉ, DE",
    "CONFORMITÉ À UNE UTILISATION PARTICULIÈRE, DE RESPECT DES",
    "COPYRIGHTS, BREVETS, MARQUES COMMERCIALES OU AUTRES DROITS.",
    "",
    "EN AUCUN CAS LE TITULAIRE DU COPYRIGHT NE POURRA ÊTRE TENU",
    "POUR RESPONSABLE EN CAS DE RÉCLAMATION, DOMMAGE OU AUTRE",
    "CONSÉQUENCE, Y COMPRIS AUCUN DOMMAGE GÉNÉRAL, SPÉCIFIQUE,",
    "INDIRECT, INCIDENT OU RÉSULTANT, QUE CE SOIT CONTRACTUELLEMENT,",
    "À TITRE DE DÉDOMMAGEMENT OU AUTREMENT, SURVENANT SUITE À",
    "L'USAGE OU L'IMPOSSIBILITÉ D'USAGE DE LA FONTE INFORMATIQUE,",
    "OU TOUTE AUTRE AFFAIRE IMPLIQUANT LA FONTE INFORMATIQUE.",
    "",
    NULL
};

struct str_lang_data ofl_str_lang_data[] = {
    { ttf_license, 0x409, ofl_eng },
    { ttf_licenseurl, 0x409, oflurl_eng },
    { ttf_license, 0x40c, ofl_fr },
    { 0, 0, NULL }
};
