.\" Manual page for sfddiff by George Williams
.\" Copyright © 2000-2002 by George Williams.
.\" Re-edited to use standard -man macros by RPC Rodgers, 23 October 2002.
.TH SFDDIFF 1 "9 March 2002"
.SH NAME
.B sfddiff - compare or merge two pfaedit sfd font files
.SH SYNOPSIS
.B sfddiff
.RB [ \-help ]
.RB [ \-ignorehints ]
.RB [ \-merge
.IR outfile ]
.RB [ \-usage ]
.RB [ \-version ]
.I sfdfile1
.I sfdfile2 
.SH DESCRIPTION
The program
.B sfddiff compares two
.IR pfaedit (1)-format
(sfd) files,
specified as command line arguments,
taking note of the following:
.TP
1)
The two fonts have different encodings.
.TP
2)
Characters are present in one font but not in the other.
.TP
3)
Characters are present in both fonts
but have different sets of outlines or references.
.TP
4)
The hints are different (optionally suppressible).
.SH OPTIONS
.TP
.B \-help
Provide a description with a list of the available options.
.TP
.B \-ignorehints
Suppress the reporting of hint differences.
.TP
.BI \-merge " outfile"
Store a merged version of the two fonts into the specified output file.
The merged data will contain everything from
.I sfdfile1
as well as any characters present in
.I sfdfile2
but not in
.RI sfdfile1 .
For any characters with different outlines or references,
the background of the the character will contain the splines from
.I sfdfile2
(sadly, references can not be placed in the background).
.TP
.B \-usage
Display the usage description.
.TP
.B \-version
Display the current version
(a six digit string containing the date stamp of the source files).
.\" .SH ENVIRONMENT
.\" .SH FILES
.\" .SH EXAMPLES
.\" .SH DIAGNOSTICS
.SH "SEE ALSO"
.BR pfaedit (1)
.LP
The HTML version of the
.I pfaedit
manual at:
.TP
\fChttp://pfaedit.sourceforge.net/\fP
.\" .SH STANDARDS
.\" .SH HISTORY
.SH AUTHOR
Copyright (C) 2000-2002 by George Williams (gww@silcom.com).
Manual page heavily rewritten and modified to use standard
.IR \-man (5)
macros by R.P.C. Rodgers (rodgers@nlm.nih.gov), 23 October 2002.
.\" .SH BUGS
.\" end of file
