#include "nomen.h"

static enum encoding enc = e_koi8_r;

static char str_Language[]  =  "Русский";
static char str_OK[]  =  "OK";
static unichar_t mnemonic_OK[]  =  'O';
static char str_Cancel[]  =  "Отмена";
static unichar_t mnemonic_Cancel[]  =  'C';
static char str_Open[]  =  "Открыть";
static unichar_t mnemonic_Open[]  =  'O';
static char str_Save[]  =  "Сохранить";
static unichar_t mnemonic_Save[]  =  'S';
static char str_Filter[]  =  "Фильтр";
static unichar_t mnemonic_Filter[]  =  'F';
static char str_New[]  =  "Новый";
static unichar_t mnemonic_New[]  =  'N';
static char str_Replace[]  =  "Заменить";
static char str_Fileexists[]  =  "Файл существует";
/* "File, %s, exists. Replace it?" */
static char str_Fileexistspre[]  =  "Файл, ";
static char str_Fileexistspost[]  =  ", существует. Заменить его?";
static char str_Createdir[]  =  "Создать каталог...";
static char str_Dirname[]  =  "Название каталога?";
static char str_Couldntcreatedir[]  =  "Невозможно создать каталог";
static char str_SelectAll[]  =  "Выбрать все";
static char mnemonic_SelectAll ='A'; 
static char *str_None  = "None";                                                                    
static char mnemonic_None ='N';
/* Menus ... */
static char str_File[]  =  "Файл";
static unichar_t mnemonic_File[]  =  'F';
static char str_Edit[]  =  "Правка";
static unichar_t mnemonic_Edit[]  =  'E';
static char str_Point[]  =  "Точка";
static unichar_t mnemonic_Point[]  =  'P';
static char str_Element[]  =  "Элемент";
static unichar_t mnemonic_Element[]  =  'l';
static char str_Hints[]  =  "Hints";
static unichar_t mnemonic_Hints[]  =  'i';
static char str_View[]  =  "Вид";
static unichar_t mnemonic_View[]  =  'V';
static char str_Metric[]  =  "Метрики";
static unichar_t mnemonic_Metric[]  =  'M';
static char str_Window[]  =  "Окно";
static unichar_t mnemonic_Window[]  =  'W';
static char str_Help[]  =  "Справка";
static unichar_t mnemonic_Help[]  =  'H';
static char str_About[] = "О программе...";
static unichar_t mnemonic_About[] = 'A';
static char str_Recent[]  =  "История";
static unichar_t mnemonic_Recent[]  =  't';
static char str_Openoutline[]  =  "Открыть контур";
static unichar_t mnemonic_Openoutline[]  =  'u';
static char str_Openbitmap[]  =  "Открыть растр";
static unichar_t mnemonic_Openbitmap[]  =  'B';
static char str_Openmetrics[]  =  "Открыть метрики";
static unichar_t mnemonic_Openmetrics[]  =  'M';
static char str_Print[]  =  "Печать...";
static unichar_t mnemonic_Print[]  =  'P';
static char str_Revertfile[]  =  "Восстановить файл";
static unichar_t mnemonic_Revertfile[]  =  'R';
static char str_Saveas[]  =  "Сохранить как...";
static unichar_t mnemonic_Saveas[]  =  'a';
static char str_Generate[]  =  "Создать шрифты...";
static unichar_t mnemonic_Generate[]  =  'G';
static char str_Import[]  =  "Импортировать...";
static unichar_t mnemonic_Import[]  =  'I';
static char str_Close[]  =  "Закрыть";
static unichar_t mnemonic_Close[]  =  'c';
static char str_Prefs[]  =  "Настройки...";
static unichar_t mnemonic_Prefs[]  =  'e';
static char str_Quit[]  =  "Выход";
static unichar_t mnemonic_Quit[]  =  'Q';
static char str_Fit[]  =  "Заполнить";
static unichar_t mnemonic_Fit[]  =  'F';
static char str_Zoomin[]  =  "Масштаб +";
static unichar_t mnemonic_Zoomin[]  =  'i';
static char str_Zoomout[]  =  "Масштаб -";
static unichar_t mnemonic_Zoomout[]  =  'o';
static char str_NextChar[]  =  "След. символ";
static unichar_t mnemonic_NextChar[]  =  'С';
static char str_PrevChar[]  =  "Пред. символ";
static unichar_t mnemonic_PrevChar[]  =  'П';
static char str_NextDefChar[] = "След. определённый символ";
static unichar_t mnemonic_NextDefChar[] = 'D';
static char str_PrevDefChar[] = "Пред. определённый символ";
static unichar_t mnemonic_PrevDefChar[] = 'a';
static char str_Goto[]  =  "Перейти";
static unichar_t mnemonic_Goto[]  =  'G';
static char str_Hidepoints[]  =  "Скрыть точки";
static unichar_t mnemonic_Hidepoints[]  =  'o';
static char str_Showpoints[]  =  "Показать точки";
static unichar_t mnemonic_Showpoints[]  =  'o';
static char str_Hiderulers[]  =  "Скрыть линейки";
static unichar_t mnemonic_Hiderulers[]  =  'R';
static char str_Showrulers[]  =  "Показать линейки";
static unichar_t mnemonic_Showrulers[]  =  'R';
static char str_Nextpoint[]  =  "След. точка";
static unichar_t mnemonic_Nextpoint[]  =  'e';
static char str_Prevpoint[]  =  "Пред. точка";
static unichar_t mnemonic_Prevpoint[]  =  'v';
static char str_Fill[]  =  "Заливка";
static unichar_t mnemonic_Fill[]  =  'l';
static char str_Undo[]  =  "Откат";
static unichar_t mnemonic_Undo[]  =  'U';
static char str_Redo[]  =  "Возврат";
static unichar_t mnemonic_Redo[]  =  'R';
static char str_Cut[]  =  "Вырезать";
static unichar_t mnemonic_Cut[]  =  't';
static char str_Copy[]  =  "Скопировать";
static unichar_t mnemonic_Copy[]  =  'C';
static char str_Copywidth[]  =  "Скопировать ширину";
static unichar_t mnemonic_Copywidth[]  =  'W';
static char str_Copyref[]  =  "Скопировать ссылку";
static unichar_t mnemonic_Copyref[]  =  'o';
static char str_Paste[]  =  "Вставить";
static unichar_t mnemonic_Paste[]  =  'P';
static char str_Clear[]  =  "Очистить";
static unichar_t mnemonic_Clear[]  =  'l';
static char str_CopyFgToBg[] = "Скопировать пер.план в фон";
static unichar_t mnemonic_CopyFgToBg[] = 'F';
static char str_Merge[]  =  "Объединить";
static unichar_t mnemonic_Merge[]  =  'M';
static char str_Unlinkref[]  =  "Разыменовать ссылку";
static unichar_t mnemonic_Unlinkref[]  =  'U';
static char str_RemoveUndoes[] = "Удалить откаты";
static unichar_t mnemonic_RemoveUndoes[] = 'e';
static char str_Fontinfo[]  =  "Информация о шрифте...";
static unichar_t mnemonic_Fontinfo[]  =  'F';
static char str_Findprobs[]  =  "Найти проблемы...";
static unichar_t mnemonic_Findprobs[]  =  'o';
static char str_Getinfo[]  =  "Сведения...";
static unichar_t mnemonic_Getinfo[]  =  'I';
static char str_ShowDependents[] = "Показать зависимые...";
static unichar_t mnemonic_ShowDependents[] = 'h';
static char str_Bitmapsavail[]  =  "Доступные растровые шрифты...";
static unichar_t mnemonic_Bitmapsavail[]  =  'A';
static char str_Regenbitmaps[]  =  "Перегенерировать растровые...";
static unichar_t mnemonic_Regenbitmaps[]  =  'B';
static char str_Autotrace[]  =  "Автотрассировка";
static unichar_t mnemonic_Autotrace[]  =  'r';
static char str_Transform[]  =  "Преобразовать...";
static unichar_t mnemonic_Transform[]  =  'T';
static char str_Stroke[]  =  "Расширить штрих...";
static unichar_t mnemonic_Stroke[]  =  'E';
static char str_Rmoverlap[]  =  "Объединить пересечения";
static unichar_t mnemonic_Rmoverlap[]  =  'v';
static char str_Simplify[]  =  "Упростить";
static unichar_t mnemonic_Simplify[]  =  'S';
static char str_CleanupChars[] = "Очистить символы";
static unichar_t mnemonic_CleanupChars[] = 'S';
static char str_AddExtrema[] = "Добавить экстремумы";
static unichar_t mnemonic_AddExtrema[] = 'x';
static char str_Align[] = "Выравнять";
static unichar_t mnemonic_Align[] = 'l';
static char str_AveragePts[] = "Средние точки";
static unichar_t mnemonic_AveragePts[] = 'A';
static char str_SpacePts[] = "Space Points"; /*new*/
static unichar_t mnemonic_SpacePts[] = 'S'; /*new*/
static char str_SpaceRegions[] = "Space Regions..."; /*new*/
static unichar_t mnemonic_SpaceRegions[] = 'R'; /*new*/
static char str_MakeParallel[] = "Сделать параллельной...";
static unichar_t mnemonic_MakeParallel[] = 'P'; /*new*/
static char str_Round2int[]  =  "Округлить";
static unichar_t mnemonic_Round2int[]  =  'I';
static char str_Buildaccent[]  =  "Создать составной символ";
static unichar_t mnemonic_Buildaccent[]  =  'u';
static char str_Buildcomposit[] = "Создать акцентир. символ";
static unichar_t mnemonic_Buildcomposit[] = 'u';
static char str_Clockwise[]  =  "По часовой";
static unichar_t mnemonic_Clockwise[]  =  'o';
static char str_Cclockwise[]  =  "Против часовой";
static unichar_t mnemonic_Cclockwise[]  =  'n';
static char str_Correct[]  =  "Исправить направление";
static unichar_t mnemonic_Correct[]  =  'C';
static char str_Corner[]  =  "Угол";
static unichar_t mnemonic_Corner[]  =  'o';
static char str_Curve[]  =  "Кривая";
static unichar_t mnemonic_Curve[]  =  'C';
static char str_Tangent[]  =  "Прямая";
static unichar_t mnemonic_Tangent[]  =  'T';
static char str_Autohint[]  =  "Автоинструкции";
static unichar_t mnemonic_Autohint[]  =  'H';
static char str_FullAutohint[] = "Полные автоинструкции";
static unichar_t mnemonic_FullAutohint[] = 'H';
static char str_ClearHints[] = "Очистить инструкции";
static unichar_t mnemonic_ClearHints[] = 'C';
static char str_Clearhstem[]  =  "Очистить гор.инструкции";
static unichar_t mnemonic_Clearhstem[]  =  'C';
static char str_Clearvstem[]  =  "Очистить верт.инструкции";
static unichar_t mnemonic_Clearvstem[]  =  'V';
static char str_Cleardstem[]  =  "Очистить диаг.инструкции";
static unichar_t mnemonic_Cleardstem[]  =  'D';
static char str_Addhhint[]  =  "Добавить гор.инструкцию";
static unichar_t mnemonic_Addhhint[]  =  'A';
static char str_Addvhint[]  =  "Добавить верт.инструкцию";
static unichar_t mnemonic_Addvhint[]  =  's';
static char str_Adddhint[]  =  "Добавить диаг.инструкцию";
static unichar_t mnemonic_Adddhint[]  =  't';
static char str_Createhhint[]  =  "Создать гор.инструкцию";
static unichar_t mnemonic_Createhhint[]  =  'r';
static char str_Createvhint[]  =  "Создать верт.инструкцию";
static unichar_t mnemonic_Createvhint[]  =  'e';
static char str_Reviewhints[]  =  "Обзор инструкций";
static unichar_t mnemonic_Reviewhints[]  =  'R';
static char str_MinimumDistance[] = "Мин. дистанция";
static unichar_t mnemonic_MinimumDistance[] = 'M';
static char str_ClearAllMD[] = "Очистить все мин.дист.";
static unichar_t mnemonic_ClearAllMD[] = 'C';
static char str_ClearSelXMD[] = "Очистить выделенные мин.дист. по X";
static unichar_t mnemonic_ClearSelXMD[] = 's'; /*new*/
static char str_ClearSelYMD[] = "Очистить выделенные мин.дист. по Y";
static unichar_t mnemonic_ClearSelYMD[] = 'e';
static char str_ClearWidthMD[] = "Clear Width MD"; /*new*/
static unichar_t mnemonic_ClearWidthMD[] = 'W';
static char str_AddxMD[] = "Добавить мин.дист. по X";
static unichar_t mnemonic_AddxMD[] = 'x';
static char str_AddMD2Width[] = "Add MD Here to Width"; /*new*/
static unichar_t mnemonic_AddxMD[] = 'x';
static char str_AddyMD[] = "Добавить мин.дист. по Y";
static unichar_t mnemonic_AddyMD[] = 'y';
static char str_RoundX[] = "Округлить X";
static unichar_t mnemonic_RoundX[] = 'R';
static char str_NoRoundX[] = "Не округлять X";
static unichar_t mnemonic_NoRoundX[] = 'N';
static char str_RoundY[] = "Округлить Y";
static unichar_t mnemonic_RoundY[] = 'u';
static char str_NoRoundY[] = "Не округлять Y";
static unichar_t mnemonic_NoRoundY[] = 'o';
static char str_Export[]  =  "Экспортировать...";
static unichar_t mnemonic_Export[]  =  't';
static char str_Palettes[]  =  "Панели";
static unichar_t mnemonic_Palettes[]  =  'P';
static char str_Tools[]  =  "Инструменты";
static unichar_t mnemonic_Tools[]  =  'T';
static char str_Layers[]  =  "Слои";
static unichar_t mnemonic_Layers[]  =  'L';
static char str_Center[]  =  "Центрировать по ширине";
static unichar_t mnemonic_Center[]  =  'C';
static char str_Thirds[]  =  "Трети по ширине";
static unichar_t mnemonic_Thirds[]  =  'T';
static char str_Setwidth[]  =  "Установить ширину...";
static unichar_t mnemonic_Setwidth[]  =  'W';
static char str_SetVWidth[] = "Set Vertical Advance..."; /*new*/
static unichar_t mnemonic_SetVWidth[] = 'V';
static char str_Setlbearing[]  =  "Установить левую границу...";
static unichar_t mnemonic_Setlbearing[]  =  'L';
static char str_Setrbearing[]  =  "Установить правую границу...";
static unichar_t mnemonic_Setrbearing[]  =  'R';
static char str_Removekern[]  =  "Удалить пары подстройки апроша";
static unichar_t mnemonic_Removekern[]  =  'v';
static char str_Mergekern[]  =  "Добавить пары подстройки апроша...";
static unichar_t mnemonic_Mergekern[]  =  'M';
static char str_24[]  =  "Контур 24 точки растра";
static unichar_t mnemonic_24[]  =  '2';
static char str_36[]  =  "Контур 36 точек растра";
static unichar_t mnemonic_36[]  =  '3';
static char str_48[]  =  "Контур 48 точек растра";
static unichar_t mnemonic_48[]  =  '4';
static char str_72[] = "Контур 72 точки растра";
static unichar_t mnemonic_72[] = '7';
static char str_96[] = "Контур 96 точек растра";
static unichar_t mnemonic_96[] = '9';
static char str_Antialias[]  =  "Сглаживание";
static unichar_t mnemonic_Antialias[]  =  'A';
static char str_Charinfo[]  =  "Информация о символе...";
static unichar_t mnemonic_Charinfo[]  =  'I';
static char str_Mergefonts[]  =  "Объединить шрифты...";
static unichar_t mnemonic_Mergefonts[]  =  'M';
static char str_Interp[]  =  "Интерполировать шрифты...";
static unichar_t mnemonic_Interp[]  =  'I';
static char str_Copyfrom[]  =  "Скопировать из";
static unichar_t mnemonic_Copyfrom[]  =  'F';
static char str_Allfonts[]  =  "всех шрифтов";
static unichar_t mnemonic_Allfonts[]  =  'A';
static char str_Displayedfont[]  =  "отображаемого шрифта";
static unichar_t mnemonic_Displayedfont[]  =  'D';
static char str_CharName[] = "Название символа";
static unichar_t mnemonic_CharName[] = 'N';
static char str_Autokern[]  =  "Автоподстройка межбуквенного пробела...";
static unichar_t mnemonic_Autokern[]  =  'K';
static char str_Autowidth[]  =  "Автоширина...";
static unichar_t mnemonic_Autowidth[]  =  'A';
static char str_Removeallkern[]  =  "Удалить все пары подстройки межбукв. пробела";
static unichar_t mnemonic_Removeallkern[]  =  'P';
static char str_Outline[]  =  "Контур";
static unichar_t mnemonic_Outline[]  =  'O';
static char str_Showgrid[]  =  "Показать сетку";
static unichar_t mnemonic_Showgrid[]  =  'G';
static char str_Hidegrid[]  =  "Скрыть сетку";
static unichar_t mnemonic_Hidegrid[]  =  'G';
static char str_Bigger[]  =  "Больший размер точки растра";
static unichar_t mnemonic_Bigger[]  =  'B';
static char str_Smaller[]  =  "Меньший размер точки растра";
static unichar_t mnemonic_Smaller[]  =  'S';
static char str_Fliph[]  =  "Отразить горизонтально";
static unichar_t mnemonic_Fliph[]  =  'H';
static char str_Flipv[]  =  "Отразить вертикально";
static unichar_t mnemonic_Flipv[]  =  'V';
static char str_Rotate90cw[]  =  "Повернуть на 90╟ по часовой";
static unichar_t mnemonic_Rotate90cw[]  =  'R';
static char str_Rotate90ccw[]  =  "Повернуть на 90╟ против часовой";
static unichar_t mnemonic_Rotate90ccw[]  =  '9';
static char str_Rotate180[]  =  "Повернуть на 180╟";
static unichar_t mnemonic_Rotate180[]  =  '1';
static char str_Skew[]  =  "Наклонить...";
static unichar_t mnemonic_Skew[]  =  'S';
static char str_MakeFirst = "Make First"; /*new*/
static char mnemonic_MakeFirst = 'k';
static char *str_CID = "CID";
static char mnemonic_CID = 'C';
static char *str_Convert2CID = "Преобразовать в CID";
static char mnemonic_Convert2CID = 'C';
static char *str_Flatten = "Flatten"; /*new*/
static char mnemonic_Flatten = 'F'; /*new*/
static char *str_InsertFont = "Вставить шрифт...";
static char mnemonic_InsertFont = 'o';
static char *str_InsertBlank = "Вставить пустой";
static char mnemonic_InsertBlank = 'B';
static char *str_RemoveFont = "Удалить шрифт";
static char mnemonic_RemoveFont = 'R';
static char *str_CIDFontInfo = "Информ. о шрифте CID...";
static char mnemonic_CIDFontInfo = 'I';

    /* Font Info dlg */
static char str_Custom[]  =  "Другое";
static char str_Isolatin1[]  =  "ISO 8859-1  (Latin1)";
static char str_Isolatin0[]  =  "ISO 8859-15  (Latin0)";
static char str_Isolatin2[]  =  "ISO 8859-2  (Latin2)";
static char str_Isolatin3[]  =  "ISO 8859-3  (Latin3)";
static char str_Isolatin4[]  =  "ISO 8859-4  (Latin4)";
static char str_Isolatin5[]  =  "ISO 8859-9  (Latin5)";
static char str_Isolatin6[]  =  "ISO 8859-10  (Latin6)";
static char str_Isolatin7[]  =  "ISO 8859-13  (Latin7)";
static char str_Isolatin8[]  =  "ISO 8859-14  (Latin8)";
static char str_Isocyrillic[]  =  "ISO 8859-5 (Кириллица)";
static char str_Koi8cyrillic[]  =  "KOI8-R (Кириллица)";
static char str_Isoarabic[]  =  "ISO 8859-6 (Арабский)";
static char str_Isogreek[]  =  "ISO 8859-7 (Греческий)";
static char str_Isohebrew[]  =  "ISO 8859-8 (Иврит)";
static char str_Isothai[] = "ISO 8859-11 (Тайский)";
static char str_Mac[]  =  "Macintosh Latin";
static char str_Win[]  =  "Windows Latin (\042ANSI\042)";
static char str_Adobestd[]  =  "Adobe Standard";
static char str_Symbol[]  =  "Symbol";
static unichar_t str_Texbase[]  =  { 0x3a4, 0x3b5, 0x3a7, ' ','B','a','s','e',  '\0' };
static char str_Unicode[]  =  "ISO 10646-1 (Unicode)";
static char str_Jis208[]  =  "JIS 208 (Kanji)";
static char str_Jis212[]  =  "JIS 212 (Kanji)";
static char str_SJIS[] = "SJIS (Kanji)";
static char str_Korean[]  =  "KSC 5601 (Корейский)";
static char str_KoreanJohab[] = "Johab (Корейский)";
static char str_KoreanWansung[] = "Wansung (Корейский)";
static char str_Chinese[]  =  "GB 2312 (Китайский)";
static char str_ChineseTrad[] = "Big5 (Китайский)";
static char str_Reducing[]  =  "Вы уменьшили число символов до меньшего\012 чем существующее количества. Некоторые символы будут удалены.\012Вы действительно этого хотите?";
static char str_Toofew[]  =  "Слишком мало символов";
static char str_Badfamilyn[]  =  "Неправильное название семейства, оно должно начинаться с буквы.";
static char str_Badfamily[]  =  "Неправильное название семейства";
static char str_Badascentdescentn[]  =  "Ascent и Descent должны быть положительными, а их сумма -- меньше 16384";
static char str_Badascentdescent[]  =  "Неподходящий Ascent/Descent";
static char str_Fontinformation[]  =  "Информация о шрифте";
static char str_Familyname[]  =  "Название семейства:";
static unichar_t mnemonic_Familyname[]  =  'F';
static char str_Fontmodifiers[]  =  "Модификаторы шрифта:";
static unichar_t mnemonic_Fontmodifiers[]  =  'M';
static char str_Humanname[]  =  "Название:";
static unichar_t mnemonic_Humanname[]  =  's';
static char str_Encoding[]  =  "Кодировка:";
static unichar_t mnemonic_Encoding[]  =  'E';
static char str_Load[]  =  "Загрузить";
static unichar_t mnemonic_Load[]  =  'L';
static char str_Makefromfont[]  =  "Создать из шрифта";
static unichar_t mnemonic_Makefromfont[]  =  'k';
static char str_Remove[]  =  "Удалить";
static unichar_t mnemonic_Remove[]  =  'M';
static char str_ForceEncoding[] = "Переименование";
static unichar_t mnemonic_ForceEncoding[] = 'F';
static char str_ForceEncodingPopup[] = "Обычно изменение кодировки перемещает символы с их старых позиций\nна их позиции в новой кодировке.\nНо если эта графа содержит отметку, то PfaEdit предполагает, что\nсимволы уже на правильных местах, но\nимеют неправильные названия и переименовывает всё\nдля совпадения с новой кодировкой.";
static char str_Italicangle[]  =  "Угол наклона:";
static unichar_t mnemonic_Italicangle[]  =  'I';
static char str_Upos[]  =  "Положение нижней линии:";
static unichar_t mnemonic_Upos[]  =  'P';
static char str_Uheight[]  =  "Высота:";
static unichar_t mnemonic_Uheight[]  =  'H';
static char str_Ascent[]  =  "Ascent:";
static unichar_t mnemonic_Ascent[]  =  'A';
static char str_Descent[]  =  "Descent:";
static unichar_t mnemonic_Descent[]  =  'D';
static char str_Copyright[]  =  "Авторское право:";
static unichar_t mnemonic_Copyright[]  =  'r';
static char str_Xuid[]  =  "XUID:";
static unichar_t mnemonic_Xuid[]  =  'X';
static char str_Numchars[]  =  "Число символов:";
static unichar_t mnemonic_Numchars[]  =  'N';
static char str_CIDRegistry[] = "Реестр CID:";
static char str_Guess[]  =  "Определить";
static unichar_t mnemonic_Guess[]  =  'G';
static char *str_FamilyNameRequired  =  "Необходимо название семейства шрифта";        
static char *str_PSNameNotNumber  =  "Имя Postscript не может быть числом";    
static char *str_BadFamilyName  =  "Недопустимое название семейства шрифта";                       
static char *str_BadModifierName  =  "Недопустимое название модификации шрифта";                   
static char *str_BadPSName  =  "Имя Postscript должно быть ASCII\n и не содержать (){}[]<>%/ или пробела";
static char *str_Names  =  "Названия";                                              
static char *str_Encoding2  =  "Кодировка";                                       
static char *str_PSGeneral  =  "PS Общее";                                     
static char *str_PSPrivate  =  "PS Специальное";                                     
static char *str_TTFNames  =  "TTF названия";                                       
static char *str_TTFValues  =  "TTF значения";                                     
static char *str_Panose  =  "Panose";                                            
static char *str_InvalidEncoding = "Неправильная кодировка";
static char *str_UniqueIDC = "UniqueID:";
static char mnemonic_UniqueIDC = 'U';
static char *str_VersionC = "Версия:";
static char mnemonic_VersionC = 'V';
static char *str_HasVerticalMetrics = "Содержит вертикальные метрики";
static char mnemonic_HasVerticalMetrics = 'V';
static char *str_VOrigin = "Нач. коорд. по вертикали:";
static char mnemonic_VOrigin = 'O';
    /* Private info */
static char *str_PrivateKey  =  "Специальный ключ";                                   
static char *str_KeyInPrivate  =  "Ключ (в специальном словаре)";                 
static char *str_Add  =  "Добавить";                                                  
static char mnemonic_Add  =  'A';
    /* TTF Values */
static char *str_UltraCondensed  =  "Ультраузкий (50%)"                                         
static char *str_ExtraCondensed  =  "Сверхузкий (62.5%)"                                       
static char *str_Condensed75  =  "Узкий (75%)"                                                  
static char *str_SemiCondensed  =  "Полуузкий (87.5%)"                                         
static char *str_Medium100  =  "Нормальный (100%)"                                                      
static char *str_SemiExpanded  =  "Полуширокий (112.5%)"                                          
static char *str_Expanded125  =  "Широкий (125%)"                                                  
static char *str_ExtraExpanded  =  "Сверхширокий (150%)"
static char *str_UltraExpanded  =  "Ультраширокий (200%)"                                          
static char *str_Thin100  =  "100 Тонкий";                                                            
static char *str_ExtraLight200  =  "200 Сверхсветлый";                                               
static char *str_Light300  =  "300 Светлый";                                                          
static char *str_Book400  =  "400 Book";                                                            
static char *str_Medium500  =  "500 Обычный";                                                        
static char *str_DemiBold600  =  "600 Полужирный";                                                   
static char *str_Bold700  =  "700 Жирный";                                                            
static char *str_Heavy800  =  "800 Сверхжирный";                                                          
static char *str_Black900  =  "900 Чёрный";                                                          
static char *str_EmbeddablePopup = "Может ли этот шрифт быть включён в скачиваемый (pdf)\nдокумент и если так, какие действия разрешены в отношении\nдокумента и шрифта.";
static char *str_Embeddable = "Встраиваемый";
static char mnemonic_Embeddable = 'E';
static char *str_LineGapPopup = "Sets the linegap field in both the OS/2 and hhea tables"; /*new*/
static char *str_LineGap = "Line Gap:"; /*new*/
static char mnemonic_LineGap = 'L';
static char *str_VLineGapPopup = "Sets the linegap field in the vhea table.\nThis is the horizontal spacing between rows\nof vertically set text."; /*new*/
static char *str_VLineGap = "Column Spacing:"; /*new*/
static char mnemonic_LineGap = 'R';
static char *str_NeverEmbeddable = "Не встраиваемый и не редактируемый";
static char *str_OnlyPrint = "Документ можно распечатывать";
static char *str_EditableDoc = "Документ можно редактировать";
static char *str_Installable = "Устанавливаемый шрифт";
static char *str_NoSubsetting = "No Subsetting"; /*new*/
static char *str_NoSubsettingPopup = "If set then the entire font must be\nembedded in a document when any character is.\nOtherwise the document creator need\nonly include the characters it uses."; /*new*/
static char *str_OnlyBitmaps = "Только растры";
static char *str_OnlyBitmapsPopup = "Только растровые шрифты могут быть встроены,\nа описания контуров -- нет.\n(Если файл шрифта не содержит растровых вариантов\nто ничего не может быть встроено)";
static char *str_Serif  =  "Serif";                                                                 
static char *str_SansSerif  =  "Sans-Serif";                                                        
static char *str_Monospace  =  "Monospace";
static char *str_Script  =  "Рукописный";                                                               
static char *str_Decorative  =  "Декоративный";                                                       
static char *str_Any  =  "Любой";                                                                     
static char *str_NoFit  =  "No Fit";                                                                
static char *str_TextDisplay  =  "Text & Display";                                                  
static char *str_Pictoral  =  "Pictoral";                                                           
static char *str_Cove  =  "Cove";                                                                   
static char *str_ObtuseCove  =  "Obtuse Cove";                                                      
static char *str_SquareCove  =  "Square Cove";                                                      
static char *str_ObtuseSquareCove  =  "Obtuse Square Cove";                                         
static char *str_Square  =  "Square";                                                               
static char *str_Thin  =  "Thin";                                                                   
static char *str_Bone  =  "Bone";                                                                   
static char *str_Exaggerated  =  "Exaggerated";                                                     
static char *str_Triangle  =  "Triangle";                                                           
static char *str_NormalSans  =  "Normal Sans";                                                      
static char *str_ObtuseSans  =  "Obtuse Sans";                                                      
static char *str_PerpSans  =  "Perp Sans";                                                          
static char *str_Flared  =  "Flared";                                                               
static char *str_Rounded  =  "Rounded";                                                             
static char *str_VeryLight  =  "Very Light";
static char *str_Light  =  "Light";                                                                 
static char *str_Book  =  "Book";                                                                   
static char *str_Medium  =  "Medium";                                                               
static char *str_Demi  =  "Demi";                                                                   
static char *str_Bold  =  "Bold";                                                                   
static char *str_Heavy  =  "Heavy";                                                                 
static char *str_Black  =  "Black";                                                                 
static char *str_Nord  =  "Nord";                                                                   
static char *str_OldStyle  =  "Древний";                                                          
static char *str_Modern  =  "Современный";                                                               
static char *str_EvenWidth  =  "Even Width";                                                        
static char *str_Expanded  =  "Широкий";                                                           
static char *str_Condensed  =  "Узкий";                                                         
static char *str_VeryExpanded  =  "Сверхширокий";                                                  
static char *str_VeryCondensed  =  "Сверхузкий";                                                
static char *str_Monospaced  = "Monospaced";                                                        
static char *str_VeryLow  = "Very Low";                                                             
static char *str_Low  = "Low";                                                                      
static char *str_MediumLow  = "Medium Low";                                                         
static char *str_MediumHigh  = "Medium High";                                                       
static char *str_High  = "High";
static char *str_VeryHigh  = "Very High";                                                           
static char *str_GradDiag  = "Gradual/Diagonal";                                                    
static char *str_GradTrans  = "Gradual/Transitional";                                               
static char *str_GradVert  = "Gradual/Vertical";                                                    
static char *str_GradHor  = "Gradual/Horizontal";                                                   
static char *str_RapidVert  = "Rapid/Vertical";                                                     
static char *str_RapidHor  = "Rapid/Horizontal";                                                    
static char *str_InstantVert  = "Instant/Vertical";                                                 
static char *str_NormalContact  = "Normal/Contact";                                                 
static char *str_NormalWeighted  = "Normal/Weighted";                                               
static char *str_NormalBoxed  = "Normal/Boxed";                                                     
static char *str_NormalFlattened  = "Normal/Flattened";                                             
static char *str_NormalRounded  = "Normal/Rounded";                                                 
static char *str_NormalOffCenter  = "Normal/Off-Center";                                            
static char *str_NormalSquare  = "Normal/Square";                                                   
static char *str_ObliqueContact  = "Oblique/Contact";                                               
static char *str_ObliqueWeighted  = "Oblique/Weighted";                                             
static char *str_ObliqueBoxed  = "Oblique/Boxed";                                                   
static char *str_ObliqueFlattened  = "Oblique/Flattened";                                           
static char *str_ObliqueRounded  = "Oblique/Rounded";                                               
static char *str_ObliqueOffCenter  = "Oblique/Off-Center";                                          
static char *str_ObliqueSquare  = "Oblique/Square"; 
static char *str_StraightArmsH  =  "Straight Arms/Horizontal";                                      
static char *str_StraightArmsW  =  "Straight Arms/Wedge";                                           
static char *str_StraightArmsV  =  "Straight Arms/Vertical";                                        
static char *str_StraightArmsSS  =  "Straight Arms/Single Serif";                                   
static char *str_StraightArmsDS  =  "Straight Arms/Double Serif";                                   
static char *str_NStraightArmsH  =  "Non-Straight Arms/Horizontal";                                 
static char *str_NStraightArmsW  =  "Non-Straight Arms/Wedge";                                      
static char *str_NStraightArmsV  =  "Non-Straight Arms/Vertical";                                   
static char *str_NStraightArmsSS  =  "Non-Straight Arms/Single Serif";                              
static char *str_NStraightArmsDS  =  "Non-Straight Arms/Double Serif";                              
static char *str_StandardTrimmed  =  "Standard/Trimmed";                                            
static char *str_StandardPointed  =  "Standard/Pointed";                                            
static char *str_StandardSerifed  =  "Standard/Serifed";                                            
static char *str_HighTrimmed  =  "High/Trimmed";                                                    
static char *str_HighPointed  =  "High/Pointed";                                                    
static char *str_HighSerifed  =  "High/Serifed";                                                    
static char *str_ConstantTrimmed  =  "Constant/Trimmed";                                            
static char *str_ConstantPointed  =  "Constant/Pointed";                                            
static char *str_ConstantSerifed  =  "Constant/Serifed";                                            
static char *str_LowTrimmed  =  "Low/Trimmed";                                                      
static char *str_LowPointed  =  "Low/Pointed";                                                      
static char *str_LowSerifed  =  "Low/Serifed"; 
static char *str_ConstantSmall  =  "Constant/Small";                                                
static char *str_ConstantStandard  =  "Constant/Standard";                                          
static char *str_ConstantLarge  =  "Constant/Large";                                                
static char *str_DuckingSmall  =  "Ducking/Small";                                                  
static char *str_DuckingStandard  =  "Ducking/Standard";                                            
static char *str_DuckingLarge  =  "Ducking/Large";                                                  
static char *str_WidthClass  = "Width Class";                                                       
static char mnemonic_WidthClass  = 'C';                                                             
static char *str_WeightClass  = "Weight Class";                                                     
static char mnemonic_WeightClass  = 'W';                                                            
static char *str_PFMFamily  = "Семейство PFM";                                                         
static char mnemonic_PFMFamily  = 'F';                                                              
static char *str_Family  = "Семейство";                                                                
static char mnemonic_Family  = 'F';                                                                 
static char *str_Serifs  = "Засечки";                                                                
static char mnemonic_Serifs  = 'S';                                                                 
static char *str_Weight  = "Насыщенность";                                                                
static char mnemonic_Weight  = 'W';                                                                 
static char *str_Proportion  = "Пропорции";                                                        
static char mnemonic_Proportion  = 'P';                                                             
static char *str_Contrast  = "Контрастность";                                                            
static char mnemonic_Contrast  = 'C';     
static char *str_StrokeVar  = "Stroke Variation";                                                   
static char mnemonic_StrokeVar  = 'V';                                                              
static char *str_ArmStyle  = "Arm Style";                                                           
static char mnemonic_ArmStyle  = 'A';                                                               
static char *str_Letterform  = "Letterform";                                                        
static char mnemonic_Letterform  = 'L';                                                             
static char *str_MidLine  = "Midline";                                                              
static char mnemonic_MidLine  = 'M';                                                                
static char *str_XHeight  = "X-Height";                                                             
static char mnemonic_XHeight  = 'X';                                                                
    /* TTF Names */
static char *str_Styles  =  "Стили";                                                               
static char *str_UniqueID  =  "UniqueID";                                                           
static char *str_Version  =  "Версия";                                                             
static char mnemonic_Version = 'V';
static char *str_Fullname  =  "Полное название";                                                           
static char *str_Trademark  =  "Торговая марка";                                                         
static char *str_Manufacturer  =  "Производитель";                                                   
static char *str_Designer  =  "Дизайнер";                                                           
static char *str_Descriptor  =  "Описание";                                                       
static char *str_VenderURL  =  "URL производителя";                                                        
static char *str_DesignerURL  =  "URL дизайнера";  
static char *str_License  =  "Лицензия";                                                             
static char *str_LicenseURL  =  "URL лицензии";                                                      
static char *str_OTFFamily  =  "Предпочтительное семейство";                                                  
static char *str_OTFStyles  =  "Предпочтительные стили";                                                  
static char *str_CompatableFull  =  "Compatable Full";                                              
static char *str_SampleText  =  "Образец текста";                                                      
static char *str_TranslateStyle = "Перевести стиль";
    /* MS Language list */
/* Language & Country (where applicable) in the native language if I can find */
/*  it, in english if I can't. Followed by the 2char language _ 2char country */
/* (again country isn't always applicable. Should basque be ES, FR? */
static char *str_Albanian  =  "Албанский sq_AL";                                                     
static char *str_Arabic  =  "Арабский ar";                                                            
static char *str_Basque  =  "Basque eu";                                                            
static char *str_Byelorussian  =  "Беларуский be_BY";                                                
static char *str_Bulgarian  =  "Болгарский bg_BG";                                                   
static char *str_Catalan  =  "Каталонский ca";                                                          
static char *str_MSChinese  =  "Китайский zh_CN";                                                     
static char *str_Croatian  =  "Хорватский hr";                                                        
static char *str_Czech  =  "Чешский cs_CZ";                                                           
static char *str_Danish  =  "Датский da_DK";                                                          
static char *str_Dutch  =  "Голандский nl_NL";
static char *str_Flemish  =  "Голандский nl_BE";                                                    
static char *str_BrEnglish  =  "Британский английский en_UK";                                             
static char *str_AmEnglish  =  "Американский английский en_US";                                            
static char *str_CaEnglish  =  "Канадский английский en_CA";                                            
static char *str_AuEnglish  =  "Австралийский английский en_AU";                                          
static char *str_NZEnglish  =  "Новозеландский английский en_NZ";                                         
static char *str_IEEnglish  =  "Ирландский английский en_IE";                                               
static char *str_Estonia  =  "Эстонский et_EE";                                                      
static char *str_Finnish  =  "Финский fi_FI";                                                         
static char *str_FRFrench  =  "Французский fr_FR";                                            
static char *str_BEFrench  =  "Бельгийский французский fr_BE";                                            
static char *str_CAFrench  =  "Канадский французский fr_CA";                                            
static char *str_CHFrench  =  "Швейцарский французский fr_CH";                                               
static char *str_LUFrench  =  "Люксембургский французский fr_LU";                                       
static char *str_DEGerman  =  "Немецкий de_DE";                                              
static char *str_CHGerman  =  "Швейцарский немецкий de_CH";                                            
static char *str_ATGerman  =  "Австрийский немецкий de_AT";                                       
static char *str_LUGerman  =  "Люксембургский немецкий de_LU";                                           
static char *str_LIGerman  =  "Лихтенштейнский немецкий de_LI";                                        
static char *str_Greek  =  "Греческий el_GR";                                                           
static char *str_Hebrew  =  "Иврит he_IL";
static char *str_Hungarian  =  "Венгерский hu_HU";                                                   
static char *str_Icelandic  =  "Исландский is_IS";                                                   
static char *str_Italian  =  "Итальянский it_IT";                                                      
static char *str_CHItalian  =  "Швейцарский итальянский it_CH";                                              
static char *str_Japanese  =  "Японский jp_JP";                                                     
static char *str_Latvian  =  "Латышский lv_LV";                                                       
static char *str_Lithuanian  =  "Литовский lt_LT";                                                 
static char *str_Norwegian  =  "Норвежский Bokmal no_NO";                                                
static char *str_NorwegianN  =  "Норвежский Nynorsk no_NO";                                              
static char *str_Polish  =  "Польский pl_PL";                                                         
static char *str_PTPortuguese  =  "Португальский pt_PT";                                      
static char *str_BRPortuguese  =  "Бразильский португальский pt_BR";                                         
static char *str_Romanian  =  "Romanian ro_RO";                                                     
static unichar_t str_Russian = { 0x420, 0x443, 0x441, 0x441, 0x43a, 0x438, 0x439, ' ', 'r','u','_','R','U',  '\0' };
static char *str_Slovak  =  "Словацкий sk_SK";                                                         
static char *str_Slovenian  =  "Словенский sl_SI";                                                   
static char *str_TradSpanish  =  "Испанский es_ES";                                           
static char *str_MXSpanish  =  "Мексиканский испанский es_MX";                                              
static char *str_ModSpanish  =  "Espaol Espaol es_ES";                                            
static char *str_Swedish  =  "Шведский sv_SE";                                                        
static char *str_Turkish  =  "Турецкий tr_TR";                                                       static char *str_Ukrainian = "Ukrainian uk_UA"; 
static char *str_Ukrainian = "Украинский uk_UA";
    /* Generate fonts */ /* savefontdlg */
static char str_Format[]  =  "Формат:";
static char str_Savefailedtitle[]  =  "Сохранение не удалось";
static char str_Outputafm[]  =  "Создавать AFM";
static char str_Outputpfm[]  =  "Создавать PFM";
static char str_Nooutlinefont[]  =  "Без контурного шрифта";
static char str_Nobitmapfonts[]  =  "Без растрового шрифта";
static char str_Afmfailedtitle[]  =  "Сохранение Afm не удалось";
static char str_Pfmfailedtitle[]  =  "Сохранение Pfm не удалось";
static char *str_SavingFont = "Сохранение шрифта";
static char *str_SavingPSFont = "Сохранение шрифта Postscript";
static char *str_SavingTTFont = "Сохранение шрифта TrueType";
static char *str_SavingCIDFont = "Сохранение шрифта CID";
static char *str_SavingAFM = "Сохранение файла AFM";
static char *str_SavingPFM = "Сохранение файла PFM";
static char *str_SavingBitmapFonts = "Сохранение растровых шрифтов";
static char *str_NotCID = "Не в формате CID";
static char *str_NotCIDOk = "You are attempting to save a CID font in a non-CID format. This is ok, but it means that only the current sub-font will be saved.\nIs that what you want?"; /*new*/
static char *str_PixelList = "Pixel List"; /*new*/
static char *str_EncodingTooLarge="Слишком большая кодировка";
static char *str_TwoBEncIn1BFont = "У вашего шрифта 2-х байтная кодировка, а вы пытаетесь сохранить его в формате, который поддерживает только однобайтные кодировки. Это значит, что вы не сможете получить доступ ни к чему после первых 256 символов без перекодирования шрифта.\n\nХотите продолжить?";
    /* Goto character ... */
static char str_Badnumberin[]  =  "Недопустимый номер в ";
static char str_Enternameofchar[]  =  "Введите название символа в шрифте";
static char str_Couldntfindchar[]  =  "Не удалось найти символ: ";
    /* Font has changed dlg */
static char str_Dontsave[]  =  "Не сохранять";
static unichar_t mnemonic_Dontsave[]  =  'D';
static char str_Fontchange[]  =  "Шрифт изменён";
/* Font %.70s in file %.70s has been changed.\nDo you want to save it? */
static char str_Fontchangepre[]  =  "Шрифт ";
static char str_Fontchangemid[]  =  " из файла ";
static char str_Fontchangepost[]  =  " был изменён.\012Хотите сохранить его?";
static char str_Fontchangerevertpost[]  =  " был изменён.\012Восстановление файла приведёт к утрате всех изменений.\012Вы этого хотите?";
    /* General messages from fontview.c */
static char str_Revert[]  =  "Восстановить";
static unichar_t mnemonic_Revert[]  =  'R';
static char str_Manywin[]  =  "Много окон";
static char str_Toomany[]  =  "Это приведёт к открытию более чем 10 окон.\012Вы действительно этого хотите?";
static char *str_MergeKernInfo = "Объединить информацию о кернинге";
static char *str_OpenPostscript = "Открыть шрифт Postscript";
static char *str_Loading = "Загрузка...";
static char *str_LoadingFontFrom = "Загружается шрифт из ";
static char *str_ReadingGlyphs = "Чтение глифов";
static char *str_InterpretingGlyphs = "Интерпретация глифов";
static char *str_CouldntOpenFontTitle = "Не удалось открыть шрифт";
static char *str_CouldntOpenFont = "Не удалось открыть шрифт (или он в неподходящем формате): %hs";
static char *str_SaveFailed = "Сбой сохранения";
static char *str_Transforming = "Преобразование...";
static char *str_Simplifying = "Упрощение...";
static char *str_AddingExtrema = "Добавление точек в экстремумах...";
static char *str_RemovingOverlap = "Удаление пересечений...";
static char *str_CorrectingDirection = "Исправление направления...";
static char *str_Rounding = "Округление до целого...";
static char *str_Autotracing = "Автотрассировка...";
static char *str_ClearDependent = "Вы пытаетесь очистить %.30hs, который ссылается на\nдругой символ. Вы уверены в том что хотите очистить его?";
static char *str_UnlinkAll = "Разыменовать все";
static char *str_dPixelBitmap = "Растр %d точек";
static char *str_RestrictedRightsFont = "Этот шрифт помечен как FSType 2 (Ограниченная\nЛицензия). Это означает, что его нельзя редактировать без\nразрешения законного владельца.\n\nУ вас есть такое разрешение?";
static char *str_RestrictedFont = "Шрифт с ограничениями";
static char *str_CloseFont = "Пожалуйста, закройте шрифт";
static char *str_CloseFontForCID = "Please close %hs before inserting it into a CID font"; /*new*/
static char *str_CIDRemoveFontCheck = "Are you sure you wish to remove sub-font %1$.40hs from the CID font %2$.40hs"; /*new*/
    /* Messages from accented characters */
static char str_Buildingaccented[]  =  "Создание акцентированных символов";
static char str_Replacearing[]  =  "Заменить е";
static char str_Areyousurearing[]  =  "Вы уверены, в том что хотите заменить е?\012Кольцо не будет соединено с A.";
static char str_Yes[]  =  "Да";
static unichar_t mnemonic_Yes[]  =  'N';
static char str_No[]  =  "Нет";
static unichar_t mnemonic_No[] = 'N';
    /* Choices from bitmap editing */
static char str_Rectangle[]  =  "Прямоугольник";
static char str_FilledRectangle[]  =  "Заполненный прямоугольник";
static char str_Elipse[]  =  "Эллипс";
static char str_FilledElipse[]  =  "Заполненный эллипс";
    /* Get Info ... */
static char str_Multiple[]  =  "Multiple";
/* "There is already a character with this Unicode encoding,\n(named %.10s at local encoding %d)\nIs that what you want?" */
static char str_Alreadycharpre[]  =  "There is already a character with this Unicode encoding,\012(named ";
static char str_Alreadycharmid[]  =  " at local encoding ";
static char str_Alreadycharpost[]  =  ")\012Is that what you want?";
static char str_Alreadycharnamed[]  =  "There is already a character with this name,\012do you want to swap names?";
/* There is already a ligature made from these components,\n(named %.10s at local encoding %d)\nIs that what you want? */
static char str_Alreadyligpre[]  =  "There is already a ligature made from these components,\012(named ";
static char str_Alreadyligmid[]  =  " at local encoding ";
static char str_Alreadyligpost[]  =  ")\012Is that what you want?";
static char str_Badligature[]  =  "A ligature may not be made up of itself";
/* "The componant %.20s is not in this font,\nIs that what you want?" */
static char str_Missingcomponantpre[]  =  "The componant ";
static char str_Missingcomponantpost[]  =  " is not in this font,\012Is that what you want?";
static char str_Done[]  =  "Сделано";
static unichar_t mnemonic_Done[]  =  'D';
static char str_Ligpop[]  =  "If this character is a ligature,\012then enter the names of the characters\012into which it decomposes";
static char *str_Show[] = "Показть";
static unichar_t mnemonic_Show[]  =  'S';
static char *str_PointInfo = "Информация о точек";
static char *str_ImageInfo = "Информация об изображении";
static char *str_ReferenceInfo = "Информация о ссылке";
static char *str_Dependents = "Зависимости";
static char *str_Offset = "Смещение";
static char *str_BaseX = "Основание X";
static char *str_BaseY = "Основание Y";
static char *str_NextCP = "След. КТ:";
static char *str_NextCPX = "След. КТ X";
static char *str_NextCPY = "След. КТ Y";
static char *str_PrevCP = "Пред. КТ:";
static char *str_PrevCPX = "Пред. КТ X";
static char *str_PrevCPY = "Пред. КТ Y";
static char *str_UnicodeName = "Название по Unicode:";
static char mnemonic_UnicodeName = 'N';
static char *str_UnicodeValue = "Значение Unicode:";
static char mnemonic_UnicodeValue = 'V';
static char *str_UnicodeChar = "Символ Unicode:";
static char mnemonic_UnicodeChar = 'h';
static char *str_SetFromName = "По названию";
static char mnemonic_SetFromName = 'a';
static char *str_SetFromValue = "По значению";
static char mnemonic_SetFromValue = 'u';
static char *str_Ligature = "Лигатура:";
static char mnemonic_Ligature = 'L';
static char *str_TransformedBy = "Transformed by:"; /*new*/
    /* Import */
static char str_Duppixelsize[]  =  "Duplicate pixelsize";
/* "The font database already contains a bitmap\nfont with this pixelsize (%d)\nDo you want to overwrite it?" */
static char str_Duppixelsizepre[]  =  "The font database already contains a bitmap\012font with this pixelsize (";
static char str_Duppixelsizepost[]  =  ")\012Do you want to overwrite it?";
static char str_NoBitmapFont = "No Bitmap Font"; /*new*/
static char str_NoBitmapFontIn = "Could not find a bitmap font in %hs"; /*new*/
    /* Private Info */
static char str_Bluequest[]  =  "This will change both BlueValues and OtherBlues.\012Do you want to continue?";
static char str_Hstemquest[]  =  "This will change both StdHW and StemSnapH.\012Do you want to continue?";
static char str_Vstemquest[]  =  "This will change both StdVW and StemSnapV.\012Do you want to continue?";
static char str_Arrayquest[]  =  "Expected array\012Procede anyway?";
static char str_Numberquest[]  =  "Expected number\012Procede anyway?";
static char str_Boolquest[]  =  "Expected boolean\012Procede anyway?";
static char str_Codequest[]  =  "Expected code\012Procede anyway?";
static char str_Badtype[]  =  "Bad type";
static char str_Delete[]  =  "Удалить";
static char mnemonic_Delete[] = 'D';
    /* Prefs */
static char str_Default[]  =  "По умолчанию";
static char *str_PrefsPopupAWS[] = "Changing the width of a character\nchanges the widths of all accented\ncharacters based on it."; /*new*/
static char *str_PrefsPopupALS[] = "Changing the left side bearing\nof a character adjusts the lbearing\nof other references in all accented\ncharacters based on it.'"; /*new*/
static char *str_PrefsPopupForNewFonts[] = "Default encoding for\nnew fonts"; /*new*/
static char *str_PrefsPopupLoc[] = "Character set used by the local\nclipboard, filesystem, etc. (only\n8bit charsets currently supported\nhere)"; /*new*/
static char *str_PrefsPopupAH[] = "AutoHint before rasterizing"; /*new*/
static char *str_PrefsPopupFN[] = "Name used for foundry field in bdf\nfont generation"; /*new*/
static char *str_PrefsPopupXU[] = "If specified this should be a space seperated list of integers each\nless than 16777216 which uniquely identify your organization\nPfaEdit will generate a random number for the final componant."; /*new*/
static char *str_PrefsPopupRulers[] = "Display rulers in the Outline Character View"; /*new*/
static char *str_PrefsPopupSepHints[] = "Have seperate controls for display horizontal and vertical hints."; /*new*/
static char *str_PrefsPopupIC[] = "In the Outline View, the Shift key constrains motion to be parallel to the ItalicAngle rather than the vertical."; /*new*/
static char *str_PrefsPopupAO[] = "The percentage of an em by which an accent is offset from its base character in Build Accent"; /*new*/
static char *str_PrefsPopupAA[] = "The number of em-units by which an arrow key will move a selected point"; /*new*/
static char *str_PrefsPopupGF[] = "Adobe has assigned the names Delta, Omega and mu\nto Increment, Ohm and micro signs respectively\nThis seems very odd to Greek font designers who use\nthe names to refer to letters of the alphabet.\nSo there is ambiguity as to what the names mean.\nSetting this flag tries to deal with the ambiguity\nby generating fonts with extra glyphs."; /*new*/
static char *str_PrefsPopupSD[] = "When the mouse pointer is within this many pixels\nof one of the various interesting features (baseline,\nwidth, grid splines, etc.) the pointer will snap\nto that feature."; /*new*/
    /* Hints */
static char *str_base  =  "Начало:";
static unichar_t mnemonic_base  =  'B';
static char *str_size  =  "Размер:";
static unichar_t mnemonic_size  =  'S';
static char *str_HStem  =  "HStem";
static unichar_t mnemonic_HStem  =  'H';
static char *str_VStem  =  "VStem";
static unichar_t mnemonic_VStem  =  'V';
static char *str_Create  =  "Создать";
static unichar_t mnemonic_Create  =  'e';
static char *str_PrevArrow  =  "< Пред.";
static unichar_t mnemonic_PrevArrow  =  'P';
static char *str_NextArrow  =  "След. >";
static unichar_t mnemonic_NextArrow  =  'N';
static char *str_CreateHint = "Создать инструкцию...";
static char *str_CreateHorizontalHint = "Create Horizontal Stem Hint"; /*new*/
static char *str_CreateVerticalHint = "Create Vertical Stem Hint"; /*new*/
    /* Auto Width/Kern */
static char *str_EnterTwoCharRange  =  "Введите два диапазона символов";
static char *str_ToBeAdjusted  =  "to be adjusted.";
static char *str_CharsLeft  =  "Символы слева";
static char *str_CharsRight  =  "Символы справа";
static char *str_All  =  "Все";
static unichar_t str_stdCharRange[]  =  { 'A','-','Z','a','-','z','0','-','9',  '\0' };
static char *str_Selected  =  "Выбранные";
static char *str_Spacing  =  "Интервал";
static char *str_TotalKerns  =  "Всего пар:";
static char *str_Threshold  =  "Порог:";
static char *str_NoCharsSelected  =  "Символы не выбраны.";
    /* Auto Trace */
static char *str_NothingToTrace  =  "Нечего трассировать";
static char *str_NoAutotrace  =  "Невозможно найти autotrace";
static char *str_NoAutotraceProg  =  "Невозможно найти программу autotrace (установите переменную окружения AUTOTRACE)";
static char *str_AdditionalAutotraceArgs = "Additional arguments for autotrace program:"; /*new*/
    /* Bitmap dlg */
static char *str_AllChars  =  "Все символы";
static char *str_SelChars  =  "Выбранные символы";
static char *str_CurChar  =  "Текущий символ";
static char *str_BadRegenSize  =  "Попытка перегенерировать размер, который не был создан: ";
static char *str_PixelSizes  =  "Размеры точек растра:";
static char *str_listPixelSizes  =  "Список текущих размеров в точках растра";
static char *str_RemovingSize  =  " Removing a size will delete it.";
static char *str_AddingSize  =  " Adding a size will create it.";
static char *str_AddingSizeScale  =  " Adding a size will create it by scaling.";
static char *str_SpecifyRegenSizes  =  "Specify bitmap sizes to be regenerated";
static char *str_PointSizes75  =  "Размер в точках на экране 75 dpi";
static char *str_PointSizes100  =  "Размер в точках на экране 100 dpi";
static char *str_ScalingBitmaps = "Scaling Bitmaps"; /*new*/
    /* Bitmap view */
/* "%s at %d from %s", charactername, pixelsize, fontname */
static char *str_bvat  =  " at ";
static char *str_bvfrom  =  " from ";
static char *str_RecalculateBitmaps  =  "Recalculate Bitmaps";
    /* BV Edit */
static char *str_skewRatio  =  "Enter the ratio of x-skew to y rise";
static char str_BadNumber[]  =  "Bad Number";
    /* Char View */
/* "%s from %s", charactername, fontname */
static char *str_cvfrom  =  " from ";
    /* CV Export */
static char *str_PixelSizeQ  =  "Размер в точках растра?";
static char *str_PixelSize  =  "Размер в точках растра:";
static char *str_BitsPerPixel  =  "Бит/Точек растра:";
static char *str_InvalidBits  =  "Допустимыми значениями для бит/точек растра являются 1, 2, 4 или 8";
    /* CV Images */
static char *str_CantFindFile  =  "Не удалось найти файл";
static char *str_BadXFigFile  =  "Неправильный файл xfig";
static char *str_BadImageFile  =  "Неправильный файл изображения";
static char *str_BadImageFileNotBitmap  =  "Неправильный файл изображения, не является растром";
static char *str_Image  =  "Изображение";
static char *str_AsBackground = "As Background"; /*new*/
static char *str_OnlyOneFont = "Only One Font"; /*new*/
static char *str_OnlyOneFontBackground = "Only one font may be imported into the background"; /*new*/
    /* CV Palettes */
static char *str_SizeOfPoints = "Размер в пунктах";
static char *str_Regular = "Regular";
static char *str_Points = "Точки:";
static char *str_RRRad = "Round Rectangle Radius";
static char *str_Polygon = "Многоугольник";
static char *str_Star = "Звезда";
static char *str_NumPSVert = "Number of star points/Polygon verteces";
/* V is an abbreviation for "Visible", and E for Editable */
static char *str_V = "V";
static char *str_E = "E";
static char *str_Layer = "Слой";
static char *str_IsEdit = "Редактируемый слой?";
static char *str_IsVis = "Видимый слой?";
/* For Foreground. Should be short */
static char *str_Fore = "Перед";
static char *str_Back = "Зад";
static char *str_Grid = "Сетка";
static char *str_HHints = "Г.инстр";
static char *str_VHints = "В.инстр";
static char *str_DHints = "Д.инстр";
static char *str_HMetrics="Г.метрики";
static char *str_VMetrics="В.метрики";
static char *str_Bitmap = "Растр";
static char *str_ShapeType  =  "Тип формы";
/* Popups */
static char *str_Pointer = "Выбрать";
static char *str_PopMag = "Увеличить (с Alt - Уменьшить)";
static char *str_AddCurvePoint = "Добавить точку кривой";
static char *str_AddCornerPoint = "Добавить угловую точку";
static char *str_AddTangentPoint = "Add a tangent point"; /*new*/
static char *str_AddPenPoint = "Add a point, then drag out its control points"; /*new*/
static char *str_popKnife = "Разделить сплайны на два";
static char *str_popRuler = "Измерить расстояние, угол между точками";
static char *str_popScale = "Масштабировать выделение";
static char *str_popFlip = "Flip the selection"; /*new*/
static char *str_popRotate = "Rotate the selection"; /*new*/
static char *str_popSkew = "Skew the selection"; /*new*/
static char *str_popRectElipse = "Rectangle or Elipse"; /*new*/
static char *str_popPolyStar = "Polygon or Star"; /*new*/
static char *str_popPencil = "Set/Clear Pixels"; /*new*/
static char *str_popLine = "Draw a Line"; /*new*/
static char *str_popShift = "Shift Entire Bitmap"; /*new*/
static char *str_popHand = "Scroll Bitmap"; /*new*/
    /* Undoes */
static char *str_BitmapPaste = "Bitmap Paste"; /*new*/
static char *str_YesToAll = "Да для всех";
static char *mnemonic_YesToAll = 'A';
static char *str_NoToAll = "Нет для всех";
static char *mnemonic_NoToAll = 'o';
/* "The clipboard contains a bitmap character of size %d,\na size which is not in your database.\nWould you like to create a bitmap font of that size,\nor ignore this character?" */
static char *str_ClipContainsPre = "The clipboard contains a bitmap character of size "; /*new*/
static char *str_ClipContainsPost = ",\na size which is not in your database.\nWould you like to create a bitmap font of that size,\nor ignore this character?"; /*new*/
static char *str_Pasting = "Pasting..."; /*new*/
static char *str_SelfRef = "Self-referential character" /*new*/
static char *str_AttemptSelfRef = "Attempt to make a character that refers to itself"; /*new*/
static char *str_BadReference = "Bad Reference"; /*new*/
static char *str_FontNoRef = "You are attempting to paste a reference to %1$hs into %2$hs.\nBut %1$hs does not exist in this font.\nWould you like to copy the original splines (or delete the reference)?"; /*new*/
static char *str_FontNoRefNoOrig = "You are attempting to paste a reference to %1$hs into %2$hs.\nBut %1$hs does not exist in this font, nor can I find the original character refered to.\nIt will not be copied."; /*new*/
static char *str_DontWarnAgain = "Don't Warn Again"; /*new*/
static char *mnemonic_DontWarnAgain = 'W';
    /* dump pfa */
static char *str_CvtPS = "Converting Postscript"; /*new*/
    /* encoding */
static char *str_BadEncFormat = "Bad encoding file format"; /*new*/
static char *str_PleaseNameEnc = "Please name this encoding"; /*new*/
/* Either insert first, second or third, or the number followed by the "th" string (5th, 6th, etc.) */
/* Please name the %d/first/second/third encoding in this file" */
static char *str_PleaseNameEncPre = "Please name the "; /*new*/
static char *str_PleaseNameEncPost = " encoding in this file"; /*new*/
static char *str_First = "First"; /*new*/
static char *str_Second = "Second"; /*new*/
static char *str_Third = "Third"; /*new*/
static char *str_th = "th"; /*new*/
static char *str_RemoveEncoding = "Remove Encoding"; /*new*/
static char *str_LoadEncoding = "Load Encoding"; /*new*/
static char *str_UseCidMap = "Use CID Map"; /*new*/
static char *str_SearchForCIDMap = "This font is based on the charset %1$.20hs-%2$.20hs-%3$d, but the best I've been able to find is %1$.20hs-%2$.20hs-%4$d.\nShall I use that or let you search?"; /*new*/
static char *str_UseIt = "Use It"; /*new*/
static char mnemonic_UseIt = 'U';
static char *str_Search = "Поиск";
static char mnemonic_Search = 'S'; /*new*/
static char *str_GiveUp = "Give Up"; /*new*/
static char mnemonic_GiveUp = 'G'; /*new*/
static char *str_AreYouSureCharset = "Are you sure you don't want to use the character set I found?"; /*new*/
static char *str_FindCharset = "Find a charset file..." /*new*/
static char *str_Browse = "Просмотр...";
static char *str_SelectCIDOrdering = "Please select a CID ordering" /*new*/
static char *str_ExtraCharsTitle = "Extraneous characters"; /*new*/
static char *str_ExtraChars = "The current encoding contains characters which I cannot map to CIDs.\nShould I delete them or add them to the end (where they may conflict with future ros definitions)?"; /*new*/

    /* fv composit */
static char *str_MissingChar = "Missing Character..."; /*new*/
static char *str_Missingdotlessi="Your font is missing the dotlessi character,\nplease add it and remake your accented characters"; /*new*/
static char *str_Missingdotlessj="Your font is missing the dotlessj character,\nplease add it and remake your accented characters"; /*new*/
    /* fv fonts */
static char *str_MergingProb = "Merging Problem"; /*new*/
static char *str_MergingFontSelf = "Merging a font with itself achieves nothing"; /*new*/
static char *str_Other = "Другое ..."
static char *str_FontToMergeInto = "Font to merge into %.20s"; /*new*/
static char *str_InterpolatingProb = "Interpolating Problem"; /*new*/
static char *str_InterpolatingFontSelf = "Interpolating a font with itself achieves nothing"; /*new*/
static char *str_Amount = "Amount"; /*new*/
static char *str_InterpBetween = "Interpolating between %.20s and:"; /*new*/
static char *str_by = "by"; /*new*/
    /* fv metrics */
static char *str_SetWidthTo = "Set Width To:"; /*new*/
static char *str_SetLBearingTo = "Set LBearing To:"; /*new*/
static char *str_SetRBearingTo = "Set RBearing To:"; /*new*/
static char *str_SetVWidthTo =    "Set Vert. Advance To:"; /*new*/
static char *str_IncrWidthBy = "Increment Width By:"; /*new*/
static char *str_IncrLBearingBy = "Increment LBearing By:"; /*new*/
static char *str_IncrRBearingBy = "Increment RBearing By:"; /*new*/
static char *str_IncrVWidthBy =   "Increment V. Adv. By:"; /*new*/
static char *str_ScaleWidthBy = "Scale Width By:"; /*new*/
static char *str_ScaleLBearingBy = "Scale LBearing By:"; /*new*/
static char *str_ScaleRBearingBy = "Scale RBearing By:"; /*new*/
static char *str_ScaleVWidthBy =   "Scale VAdvance By:"; /*new*/
    /* Import bdf */
static char *str_PixelSizeFont = "What is the pixel size of the font in this file?"; /*new*/
static char *str_CouldNotOpenFile = "Couldn't open file" /*new*/
static char *str_CouldNotOpenFileName = "Couldn't open file %.200hs" /*new*/
static char *str_NotBdfFile = "Not a bdf file" /*new*/
static char *str_NotBdfFileName = "Not a bdf file %.200hs" /*new*/
static char *str_NotPkFile = "Not a pk file" /*new*/
static char *str_NotPkFileName = "Not a (metafont) pk file %.200hs" /*new*/
static char *str_LoadingFrom = "Загрузка шрифта из %.100hs";
static char *str_DuplicateName = "Duplicate Name"; /*new*/
static char *str_DuplicateCharName = "Duplicate character name (%hs) in font"; /*new*/
    /* problems */
static char *str_ProbOpenPath  =  "Выбранный контур не образует замкнутый цикл";
static char *str_ProbPointsTooClose  =  "Выбранные точки слишком близки друг к другу";
static char *str_ProbMissingExtreme  =  "Выбранная кривая не имеет точек в экстремумах";
static char *str_ProbXNear  =  "Координата X выбранной точки возле указанного значения";
static char *str_ProbYNear  =  "Координата Y выбранной точки возле указанного значения";
static char *str_ProbYBase  =  "Координата Y выбранной точки возле базовой линии";
static char *str_ProbYXHeight  =  "Координата Y выбранной точки возле xheight";
static char *str_ProbYCapHeight  =  "Координата Y выбранной точки возле cap height";
static char *str_ProbYAs  =  "Координата Y выбранной точки возле ascender height";
static char *str_ProbYDs  =  "Координата Y выбранной точки возле descender height";
static char *str_ProbLineHor  =  "Выбранный сегмент почти горизонтален";
static char *str_ProbLineVert  =  "Выбранный сегмент почти вертикален";
static char *str_ProbLineItal  =  "Выбранный сегмент наклонён почти на угол наклона шрифта";
static char *str_ProbAboveHor = "The control point above the selected point is nearly horizontal"; /*new*/
static char *str_ProbAboveVert = "The control point above the selected point is nearly vertical"; /*new*/
static char *str_ProbAboveItal = "The control point above the selected point is near the italic angle"; /*new*/
static char *str_ProbBelowHor = "The control point below the selected point is nearly horizontal"; /*new*/
static char *str_ProbBelowVert = "The control point below the selected point is nearly vertical"; /*new*/
static char *str_ProbBelowItal = "The control point below the selected point is near the italic angle"; /*new*/
static char *str_ProbLeftHor = "The control point left of the selected point is nearly horizontal"; /*new*/
static char *str_ProbLeftVert = "The control point left of the selected point is nearly vertical"; /*new*/
static char *str_ProbLeftItal = "The control point left of the selected point is near the italic angle"; /*new*/
static char *str_ProbRightHor = "The control point right of the selected point is nearly horizontal"; /*new*/
static char *str_ProbRightVert = "The control point right of the selected point is nearly vertical"; /*new*/
static char *str_ProbRightItal = "The control point right of the selected point is near the italic angle"; /*new*/
static char *str_ProbPtNearHHint  =  "Выбранная точка почти на горизонтали stem hint";
static char *str_ProbPtNearVHint  =  "Выбранная точка почти на вертикали stem hint";
static char *str_ProbHintHWidth  =  "Этот символ содержит горизонтальный hint почти указанной ширины";
static char *str_ProbHintVWidth  =  "Этот символ содержит вертикальный hint почти указанной ширины";
static char *str_ProbHintControl  =  "Этот hint не управляет ни одной точкой";
static char *str_ProbExpectedCounter = "This path should have been drawn in a counter-clockwise direction"; /*new*/
static char *str_ProbExpectedClockwise = "This path should have been drawn in a clockwise direction"; /*new*/
static char *str_ProbFlippedRef = "This reference has been flipped, so the paths in it are drawn backwards" /*new*/
static char *str_ProbAboveOdd = "The control point above the selected point is outside the spline segment"; /*new*/
static char *str_ProbBelowOdd = "The control point below the selected point is outside the spline segment"; /*new*/
static char *str_ProbRightOdd = "The control point right of the selected point is outside the spline segment"; /*new*/
static char *str_ProbLeftOdd = "The control point left of the selected point is outside the spline segment"; /*new*/
static char *str_ProbCIDMult = "This character is defined in more than one of the CID subfonts"; /*new*/
static char *str_ProbCIDBlank = "This character is not defined in any of the CID subfonts"; /*new*/
static char *str_ProbExplain  =  "Объяснение проблемы";
static char *str_Stop  =  "Стоп";
static char *mnemonic_Stop  =  'S';
static char *str_Next  =  "След.";
static char *mnemonic_Next  =  'N';
static char *str_OpenPaths  =  "Открытый контур";
static char *mnemonic_OpenPaths  =  'P';
static char *str_OpenPathsPopup  =  "Все контуры должны образовывать замкнутые циклы, не содержащие концов";
static char *str_Points2Close  =  "Точки слишком близко";
static char *mnemonic_Points2Close  =  't';
static char *str_Points2ClosePopup  =  "Если две соединёные точки на одном контуре расположены на расстоянии\n меньшем чем emunits они будут вызывать проблемы с некоторыми командами\npfaedit. Однако PostScript это не запрещает.";
/*static char *str_MissingExtrema = "Missing Extrema";
/*static char *mnemonic_MissingExtrema = 'E';
/*static char *str_MissingExtremaPopup = "Ghostview (perhaps other interpreters) has a problem when a\nhint exists without any points that lie on it. Usually this is because\nthere are no points at the extrema";*/
static char *str_XNear  =  "Близкий X";
static char *mnemonic_XNear  =  'X';
static char *str_XNearPopup  =  "Позволяет вам проверить, что вертикальные элементы в\n нескольких символах начинаются в одинаковом месте.";
static char *str_YNear  =  "Близкий Y";
static char *mnemonic_YNear  =  'Y';
static char *str_YNearPopup  =  "Позволяет вам проверить, что горизонтальные элементы в\n нескольких символах начинаются в одинаковом месте.";
static char *str_YNearStd  =  "Y возле стандартных высот";
static char *mnemonic_YNearStd  =  'S';
static char *str_YNearStdPopup  =  "Позволяет вам найти точки почти на\n базовой линии, высотах xheight,cap height,\nascender, descender.";
static char *str_LineStd  =  "Края почти горизонтальны/вертикальны";
static char *str_LineStd2  =  "Края почти горизонтальны/вертикальны/наклонны";
static char *mnemonic_LineStd  =  'E';
static char *str_LineStdPopup  =  "Позволяет вам найти линии, которые почти,\nно не совершенно горизонтальны или вертикальны\n(или почти совпадают с углом наклона шрифта).";
static char *str_CpStd = "Управляющие точки почти горизонтальны/вертикальны";
static char *str_CpStd2 = "Управляющие точки почти горизонтальны/вертикальны/под углом наклона шрифта";
static char *mnemonic_CpStd = 'C';
static char *str_CpStdPopup = "Allows you to find control points which are almost,\nbut not quite horizontal or vertical\nfrom their base point\n(or at the italic angle)."; /*new*/
static char *str_CpOdd = "Control Points beyond spline"; /*new*/
static char *mnemonic_CpOdd = 'b';
static char *str_CpOddPopup = "Allows you to find control points which when projected\nonto the line segment between the two end points lie\noutside of those end points"; /*new*/
static char *str_HintNoPt  =  "Инструкция не управляет точками";
static char *mnemonic_HintNoPt  =  'H';
static char *str_HintNoPtPopup  =  "Ghostview (и возможно другие интерпретаторы) имеет проблемы с \nhint, которым не принадлежит ни одной точки.";
static char *str_PtNearHint  =  "Точки возле краёв инструкции";
static char *mnemonic_PtNearHint  =  'P';
static char *str_PtNearHintPopup  =  "Часто если точка чуть-чуть отличается от hint\nпо причине того, что элемент состоит из\nнескольких сегментов, и один из них\nимеет неправильную ширину.";
static char *str_HintWidth  =  "Близкая ширина инструкции";
static char *mnemonic_HintWidth  =  'W';
static char *str_HintWidthPopup  =  "Позволяет вам проверить, что элементы имеют одинаковые ширины..";
static char *str_CheckDirection = "Check outermost paths clockwise"; /*new*/
static char *mnemonic_CheckDirection = 'o';
static char *str_CheckDirectionPopup = "Postscript and TrueType require that paths be drawn\nin a clockwise direction. This lets you check that they\nare."; /*new*/
static char *str_CheckFlippedRefs = "Check flipped references"; /*new*/
static char *mnemonic_CheckFlippedRefs = 'r'; /*new*/
static char *str_CheckFlippedRefsPopup = "Postscript and TrueType require that paths be drawn\nin a clockwise direction. If you have a reference\nthat has been flipped then the paths in that reference will\nprobably be counter-clockwise. You should unlink it and do\nCorect direction on it."; /*new*/
static char *str_CIDMultiple = "Check for CIDs defined twice"; /*new*/
static char *mnemonic_CIDMultiple = 'O'; /*new*/
static char *str_CIDMultiplePopup = "Check whether a CID is defined in more than one sub-font"; /*new*/
static char *str_CIDBlank = "Check for undefined CIDs"; /*new*/
static char *mnemonic_CIDBlank = 'O'; /*new*/
static char *str_CIDBlankPopup = "Check whether a CID is undefined in all sub-fonts"; /*new*/
static char *str_PointsNear  =  "Точки \"Близки\", если меньше";
static char *mnemonic_PointsNear  =  'N';
static char *str_Near  =  "Близки";
static char *str_ExplainErr  =  "Остановка и объяснение после каждой ошибки";
static char *mnemonic_ExplainErr  =  'A';
static char *str_IgnoreProblemFuture = "Ignore this problem in the future"; /*new*/
/* "Found %g, expected %g" */
static char *str_Found  =  "Найдено ";
static char *str_Expected  =  ", ожидалось ";
	/* Meta font */
static char *str_MetaFont  =  "Мета Шрифт...";
static char mnemonic_MetaFont = 'M';
static char *str_CounterTooSmallT  =  "Counter Too Small";
static char *str_CounterTooSmall  =  "A counter was requested to be too small, it has been pegged at its minimum value";
static char *str_Simple  =  "Простой";
static char *str_Advanced  =  "Расширенный";
static char *str_Embolden  =  "Утолщённый";
static char *str_Condense  =  "Сжатый";
static char *str_Expand  =  "Расширенный";
static char *str_Stems  =  "Осн.элементы";
static char *str_HCounters  =  "H Counters";
static char *str_VCounters  =  "V Counters";
static char *str_StemScale  =  "Масштаб основных элементов:";
static char *str_CounterScale  =  "Scale Counters By:";
static char *str_XHeightFrom  =  "Высота с:";
static char *str_To  =  "на:";
static char *str_MetamorphosingFont = "Metamorphosing Font..."; /*new*/
	/* to ttf */
static char *str_PickFont = "Pick a font, any font..."; /*new*/
static char *str_MultipleFontsPick = "There are multiple fonts in this file, pick one"; /*new*/
static char *str_AutoHintingFont = "Auto Hinting Font..."; /*new*/
static char *str_SavingOpenTypeFont = "Saving OpenType Font"; /*new*/
static char *str_LoadBitmapFonts = "Load bitmap fonts?"; /*new*/
static char *str_LoadTTFBitmaps = "Do you want to load the bitmap fonts embedded in this true/open type file?\n(And if so, which)"; /*new*/
static char *str_BadEncoding = "Bad Encoding"; /*new*/
static char *str_ExtraneousSingleByte = "There is a single byte character (%d) using one of the slots needed for double byte characters"; /*new*/
static char *str_OutOfEncoding = "There is a character (%d) which cannot be encoded"; /*new*/
static char *str_NotNormallyEncoded = "There is a character (%d) which is not normally in the encoding"; /*new*/
	/* Spline Fill */
static char *str_Rasterizing = "Растеризация...";
static char *str_GenBitmap = "Создание растрового шрифта";
static char *str_GenAntiAlias = "Generating anti-alias font"; /*new*/
/* "%d pixels" (for the size of the font being rasterized) */
static char *str_Pixels = " pixels"; /*new*/
	/* print */
static char *str_PrintingFont = "Printing Font"; /*new*/
static char *str_GeneratingPostscriptFont = "Generating Postscript Font"; /*new*/
static char *str_FailedGenPost = "Failed to generate postscript font"; /*new*/
static char *str_PageSetup = "Page Setup"; /*new*/
static char *str_Setup = "Setup"; /*new*/
static char mnemonic_Setup = 'e'; /*new*/
static char *str_ToFile = "To File"; /*new*/
static char mnemonic_ToFile = 'F'; /*new*/
static char *str_PageSize = "PageSize:"; /*new*/
static char mnemonic_PageSize = 'S'; /*new*/
static char *str_Copies = "Copies:"; /*new*/
static char mnemonic_Copies = 'C'; /*new*/
static char *str_Printer = "Printer:"; /*new*/
static char mnemonic_Printer = 'P'; /*new*/
static char *str_PrintToFile = "Print To File..."; /*new*/
static char *str_Pointsize = "Pointsize:"; /*new*/
static char mnemonic_Pointsize = 'P'; /*new*/
static char *str_FullFont = "Full Font Display"; /*new*/
static char mnemonic_FullFont = 'F';
static char *str_FullPageChar = "Full Page Character"; /*new*/
static char mnemonic_FullPageChar = 'C'; /*new*/
static char *str_FullPageChars = "Full Page Characters"; /*new*/
static char mnemonic_FullPageChars = 'C'; /*new*/
static char mnemonic_SampleText = 'S'; /*new*/
static char *str_SampleTextC = "Sample Text:"; /*new*/
static char mnemonic_SampleTextC = 'T'; /*new*/
static char *str_FailedOpenTemp = "Failed to open temporary output file"; /*new*/
    /* alignment */
static char *str_CoordinateAlongWhich = "Coordinate along which to space"; /*new*/
static char *str_X = "X"; /*new*/
static char mnemonic_X = 'X'; /*new*/
static char *str_Y = "Y"; /*new*/
static char mnemonic_Y = 'Y'; /*new*/
static char *str_MaximumDistanceBetweenPts = "Maximum distance between points in a region"; /*new*/
static char mnemonic_MaximumDistanceBetweenPts = 'M'; /*new*/
static char *str_NotEnoughLines = "Not enough lines"; /*new*/
static char *str_CantParallel = "Can't Parallel"; /*new*/
static char *str_ShareCommonEndpoint = "These two lines share a common endpoint, I can't make them parallel"; /*new*/
    /* parsettf */
static char *str_ReadingNames = "Reading Names"; /*new*/
static char *str_FixingupReferences = "Fixing up References"; /*new*/
static char *str_NoBitmaps = "No Bitmap Strikes"; /*new*/
static char *str_NoBitmapsInTTF = "No (useable) bitmap strikes in this TTF font: %hs"; /*new*/
    /* sfd */
static char *str_Saving = "Saving..."; /*new*/
static char *str_SavingDb = "Saving Spline Font Database"; /*new*/
static char *str_SavingOutlines = "Saving Outlines"; /*new*/
static char *str_SavingBitmaps = "Saving Bitmaps"; /*new*/
    /* start.c */
static char *str_PfaEdit = "PfaEdit"; /*new*/
    /* cvpointer.c */
static char *str_NegativeWidth = "Negative Width"; /*new*/
static char *str_NegativeWidthCheck = "Negative character widths are not allowed in TrueType\nDo you really want a negative width?"; /*new*/
    /* hanyang.c */
static char *str_Hangul = "Hangul"; /*new*/
static char mnemonic_Hangul = 'H'; /*new*/
static char *str_NewComposition = "New Composition..."; /*new*/
static char mnemonic_NewComposition = 'N'; /*new*/
static char *str_ModifyComposition = "Modify Composition..."; /*new*/
static char mnemonic_ModifyComposition = 'M'; /*new*/
static char *str_BuildSyllables = "Build Syllables"; /*new*/
static char mnemonic_BuildSyllables = 'B'; /*new*/
static char *str_ChoSung = "Cho-Sung"; /*new*/
static char *str_JungSung = "Jung-Sung"; /*new*/
static char *str_JongSung = "Jong-Sung"; /*new*/
static char *str_ChoSungC = "Cho-Sung:"; /*new*/
static char *str_JungSungC = "Jung-Sung:"; /*new*/
static char *str_JongSungC = "Jong-Sung:"; /*new*/
static char *str_Mapping = "Mapping..."; /*new*/
static char mnemonic_Mapping = 'M'; /*new*/
static char *str_Width = "Width..."; /*new*/
static char mnemonic_Width = 'W'; /*new*/
static char *str_Reset = "Reset"; /*new*/
static char *str_LoadFrom = "Load From..."; /*new*/
static char mnemonic_LoadFrom = 'L'; /*new*/
static char *str_BadWidth = "Bad Number for Width"; /*new*/
static char *str_BadGroup = "Bad Number for Group"; /*new*/
static char *str_JamoHoleTitle = "Unused glyph variant"; /*new*/
static char *str_JamoHole = "For group %d of %s, glyph variant %d is not used but %d is used.\nProcede anyway?"; /*new*/
static char *str_NoRules = "No Rules"; /*new*/
static char *str_FileHasNoRules = "%.100hs contains no composition rules"; /*new*/
    /* Need a different mnemonic */
static char *str_AddAll = "Add All"; /*new*/
static char mnemonic_AddAll = 'd'; /*new*/
static char *str_DisplayCompositions = "Display Compositions..."; /*new*/
static char mnemonic_DisplayCompositions = 'D'; /*new*/
static char *str_NoGroups = "This varient of this jamo is not actually used"; /*new*/
static char *str_UniVarient = "Unicode %04X, Varient %d, %s"; /*new*/
static char *str_BuildingKoreanFont = "Building Korean Font"; /*new*/
    /* Transform */
static char *str_TransformBackground = "Transform Background Too"; /*new*/
static char mnemonic_TransformBackground = 'B'; /*new*/
    /* start (about box) */
static char *str_FreePress = "A free press discriminates\nagainst the illiterate."; /*new*/

static int num_buttonsize  =  70;
