/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FontView (void);
GtkWidget* create_FontForgeSplash (void);
GtkWidget* create_CharView (void);
GtkWidget* create_MetricsView (void);
GtkWidget* create_BitmapView (void);
GtkWidget* create_FontInfo (void);
GtkWidget* create_FontViewShowMetrics (void);
GtkWidget* create_FontViewPopupMenu (void);
